# Additional items to reach 683 total
MORE_ITEMS = [
    # More packaging items
    {"name": "Takeaway Box 500 ML", "category": "Packaging", "unit": "PCS", "standard_price": 4.50, "vendor": "ECOTEGRITY", "hsn_code": "3923", "gst_rate": 18.0},
    {"name": "Takeaway Box 750 ML", "category": "Packaging", "unit": "PCS", "standard_price": 5.50, "vendor": "ECOTEGRITY", "hsn_code": "3923", "gst_rate": 18.0},
    {"name": "Takeaway Box 1000 ML", "category": "Packaging", "unit": "PCS", "standard_price": 6.50, "vendor": "ECOTEGRITY", "hsn_code": "3923", "gst_rate": 18.0},
    {"name": "Paper Cup 150 ML", "category": "Packaging", "unit": "PKT", "standard_price": 145.0, "vendor": "ECOTEGRITY", "hsn_code": "48193000", "gst_rate": 18.0},
    {"name": "Paper Cup 200 ML", "category": "Packaging", "unit": "PKT", "standard_price": 165.0, "vendor": "ECOTEGRITY", "hsn_code": "48193000", "gst_rate": 18.0},
    {"name": "Paper Plate 6 Inch", "category": "Packaging", "unit": "PKT", "standard_price": 120.0, "vendor": "ECOTEGRITY", "hsn_code": "48236900", "gst_rate": 18.0},
    {"name": "Paper Plate 8 Inch", "category": "Packaging", "unit": "PKT", "standard_price": 150.0, "vendor": "ECOTEGRITY", "hsn_code": "48236900", "gst_rate": 18.0},
    {"name": "Paper Napkin White", "category": "Packaging", "unit": "PKT", "standard_price": 85.0, "vendor": "BEETA TISSUE", "hsn_code": "48183000", "gst_rate": 18.0},
    {"name": "Tissue Box 100 Sheet", "category": "Packaging", "unit": "BOX", "standard_price": 45.0, "vendor": "BEETA TISSUE", "hsn_code": "48181000", "gst_rate": 18.0},
    {"name": "Wet Tissue Pack", "category": "Packaging", "unit": "PKT", "standard_price": 65.0, "vendor": "BEETA TISSUE", "hsn_code": "48181000", "gst_rate": 18.0},
    
    # More vegetables
    {"name": "Red Onion", "category": "Vegetables", "unit": "KG", "standard_price": 40.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "White Onion", "category": "Vegetables", "unit": "KG", "standard_price": 45.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Shallot Onion", "category": "Vegetables", "unit": "KG", "standard_price": 120.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Celery", "category": "Vegetables", "unit": "KG", "standard_price": 180.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Leeks", "category": "Vegetables", "unit": "KG", "standard_price": 220.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Fennel Bulb", "category": "Vegetables", "unit": "KG", "standard_price": 280.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Turnip", "category": "Vegetables", "unit": "KG", "standard_price": 40.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Parsnip", "category": "Vegetables", "unit": "KG", "standard_price": 180.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Kohlrabi", "category": "Vegetables", "unit": "KG", "standard_price": 80.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Kale", "category": "Vegetables", "unit": "KG", "standard_price": 180.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Swiss Chard", "category": "Vegetables", "unit": "KG", "standard_price": 160.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Rocket Leaves", "category": "Vegetables", "unit": "PKT", "standard_price": 120.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Watercress", "category": "Vegetables", "unit": "PKT", "standard_price": 100.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Microgreens Mix", "category": "Vegetables", "unit": "PKT", "standard_price": 180.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Edible Flowers", "category": "Vegetables", "unit": "PKT", "standard_price": 250.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Red Cabbage", "category": "Vegetables", "unit": "KG", "standard_price": 45.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Savoy Cabbage", "category": "Vegetables", "unit": "KG", "standard_price": 80.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Brussels Sprouts", "category": "Vegetables", "unit": "KG", "standard_price": 280.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Artichoke Fresh", "category": "Vegetables", "unit": "KG", "standard_price": 450.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Okra", "category": "Vegetables", "unit": "KG", "standard_price": 60.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Ridge Gourd", "category": "Vegetables", "unit": "KG", "standard_price": 40.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Bottle Gourd", "category": "Vegetables", "unit": "KG", "standard_price": 35.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Bitter Gourd", "category": "Vegetables", "unit": "KG", "standard_price": 50.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Snake Gourd", "category": "Vegetables", "unit": "KG", "standard_price": 45.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Ivy Gourd", "category": "Vegetables", "unit": "KG", "standard_price": 80.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Ash Gourd", "category": "Vegetables", "unit": "KG", "standard_price": 30.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Cluster Beans", "category": "Vegetables", "unit": "KG", "standard_price": 80.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Broad Beans", "category": "Vegetables", "unit": "KG", "standard_price": 90.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Lima Beans", "category": "Vegetables", "unit": "KG", "standard_price": 120.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Yard Long Beans", "category": "Vegetables", "unit": "KG", "standard_price": 80.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    
    # More Indian Grocery
    {"name": "Chana Dal 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 95.0, "vendor": "PRIME FOOD", "hsn_code": "071320", "gst_rate": 0},
    {"name": "Moong Dal Yellow 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 140.0, "vendor": "PRIME FOOD", "hsn_code": "071320", "gst_rate": 0},
    {"name": "Moong Dal Green 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 125.0, "vendor": "PRIME FOOD", "hsn_code": "071320", "gst_rate": 0},
    {"name": "Urad Dal Black 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 165.0, "vendor": "PRIME FOOD", "hsn_code": "071320", "gst_rate": 0},
    {"name": "Urad Dal White 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 175.0, "vendor": "PRIME FOOD", "hsn_code": "071320", "gst_rate": 0},
    {"name": "Kabuli Chana 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 125.0, "vendor": "PRIME FOOD", "hsn_code": "071320", "gst_rate": 0},
    {"name": "Kala Chana 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 95.0, "vendor": "PRIME FOOD", "hsn_code": "071320", "gst_rate": 0},
    {"name": "Lobiya 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 110.0, "vendor": "PRIME FOOD", "hsn_code": "071350", "gst_rate": 0},
    {"name": "Chawli 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 105.0, "vendor": "PRIME FOOD", "hsn_code": "071350", "gst_rate": 0},
    {"name": "Horse Gram 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 85.0, "vendor": "PRIME FOOD", "hsn_code": "071339", "gst_rate": 0},
    {"name": "Split Peas Yellow", "category": "Indian Grocery", "unit": "PKT", "standard_price": 95.0, "vendor": "PRIME FOOD", "hsn_code": "071310", "gst_rate": 0},
    {"name": "Split Peas Green", "category": "Indian Grocery", "unit": "PKT", "standard_price": 105.0, "vendor": "PRIME FOOD", "hsn_code": "071310", "gst_rate": 0},
    {"name": "Masoor Sabut", "category": "Indian Grocery", "unit": "PKT", "standard_price": 95.0, "vendor": "PRIME FOOD", "hsn_code": "071340", "gst_rate": 0},
    {"name": "Moth Dal 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 145.0, "vendor": "PRIME FOOD", "hsn_code": "071339", "gst_rate": 0},
    {"name": "Mix Dal 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 120.0, "vendor": "PRIME FOOD", "hsn_code": "071390", "gst_rate": 0},
    {"name": "Poha Thick 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 55.0, "vendor": "LOTS", "hsn_code": "19041090", "gst_rate": 5.0},
    {"name": "Poha Thin 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 55.0, "vendor": "LOTS", "hsn_code": "19041090", "gst_rate": 5.0},
    {"name": "Murmura 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 45.0, "vendor": "LOTS", "hsn_code": "19041090", "gst_rate": 5.0},
    {"name": "Sabudana 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 135.0, "vendor": "LOTS", "hsn_code": "19031000", "gst_rate": 5.0},
    {"name": "Singhara Atta 500 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 85.0, "vendor": "LOTS", "hsn_code": "11062090", "gst_rate": 0},
    {"name": "Kuttu Atta 500 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 95.0, "vendor": "LOTS", "hsn_code": "11029090", "gst_rate": 0},
    {"name": "Rajgira Atta 500 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 125.0, "vendor": "LOTS", "hsn_code": "11029090", "gst_rate": 0},
    {"name": "Besan 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 95.0, "vendor": "LOTS", "hsn_code": "11031300", "gst_rate": 5.0},
    {"name": "Maida 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 45.0, "vendor": "LOTS", "hsn_code": "11010000", "gst_rate": 5.0},
    {"name": "Sooji Coarse 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 55.0, "vendor": "LOTS", "hsn_code": "11031900", "gst_rate": 5.0},
    {"name": "Dalia 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 65.0, "vendor": "LOTS", "hsn_code": "11032090", "gst_rate": 0},
    {"name": "Oats 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 185.0, "vendor": "LOTS", "hsn_code": "11042200", "gst_rate": 5.0},
    {"name": "Jowar 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 65.0, "vendor": "LOTS", "hsn_code": "10070010", "gst_rate": 0},
    {"name": "Bajra 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 55.0, "vendor": "LOTS", "hsn_code": "10082900", "gst_rate": 0},
    {"name": "Makka Atta 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 45.0, "vendor": "LOTS", "hsn_code": "11022000", "gst_rate": 5.0},
    {"name": "Rice Flour 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 55.0, "vendor": "LOTS", "hsn_code": "11029010", "gst_rate": 5.0},
    
    # More Chinese/Asian grocery
    {"name": "Chilli Bean Paste", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Doubanjiang", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 380.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Gochujang", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 420.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Gochugaru", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 350.0, "vendor": "FOOD MONDE", "hsn_code": "9042211", "gst_rate": 5.0},
    {"name": "Doenjang", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 380.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Ssamjang", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 350.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Korean BBQ Sauce", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Bulgogi Marinade", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 285.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Japchae Noodles", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 220.0, "vendor": "FOOD MONDE", "hsn_code": "19021900", "gst_rate": 5.0},
    {"name": "Korean Rice Cake", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "19059090", "gst_rate": 5.0},
    {"name": "Tteok Oval", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 295.0, "vendor": "FOOD MONDE", "hsn_code": "19059090", "gst_rate": 5.0},
    {"name": "Korean Chili Paste", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 350.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Korean Sesame Oil", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 450.0, "vendor": "FOOD MONDE", "hsn_code": "15155000", "gst_rate": 5.0},
    {"name": "Perilla Oil", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 520.0, "vendor": "FOOD MONDE", "hsn_code": "15159090", "gst_rate": 5.0},
    {"name": "Rice Paper Triangle", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 195.0, "vendor": "FOOD MONDE", "hsn_code": "19019090", "gst_rate": 5.0},
    {"name": "Spring Roll Pastry", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 165.0, "vendor": "FOOD MONDE", "hsn_code": "19019090", "gst_rate": 5.0},
    {"name": "Gyoza Wrapper", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 145.0, "vendor": "FOOD MONDE", "hsn_code": "19019090", "gst_rate": 5.0},
    {"name": "Dumpling Wrapper", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 125.0, "vendor": "FOOD MONDE", "hsn_code": "19019090", "gst_rate": 5.0},
    {"name": "Egg Roll Wrapper", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 135.0, "vendor": "FOOD MONDE", "hsn_code": "19019090", "gst_rate": 5.0},
    {"name": "Laksa Paste", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Tom Yum Paste", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 265.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Massaman Curry Paste", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 295.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Panang Curry Paste", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 285.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Rendang Paste", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 310.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Nasi Goreng Paste", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 245.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Pho Paste", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 275.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Banh Mi Sauce", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 220.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Hoisin Cooking Sauce", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 245.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Kung Pao Sauce", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 235.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Mongolian Sauce", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 255.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    
    # More Beverages
    {"name": "Fresh Lime Soda", "category": "Beverage", "unit": "BTL", "standard_price": 35.0, "vendor": "LOTS", "hsn_code": "220210", "gst_rate": 40.0},
    {"name": "Ginger Beer", "category": "Beverage", "unit": "BTL", "standard_price": 85.0, "vendor": "LOTS", "hsn_code": "220210", "gst_rate": 40.0},
    {"name": "Lychee Juice 1 L", "category": "Beverage", "unit": "BTL", "standard_price": 145.0, "vendor": "LOTS", "hsn_code": "20098990", "gst_rate": 12.0},
    {"name": "Mango Juice 1 L", "category": "Beverage", "unit": "BTL", "standard_price": 125.0, "vendor": "LOTS", "hsn_code": "20098990", "gst_rate": 12.0},
    {"name": "Guava Juice 1 L", "category": "Beverage", "unit": "BTL", "standard_price": 115.0, "vendor": "LOTS", "hsn_code": "20098990", "gst_rate": 12.0},
    {"name": "Passion Fruit Pulp", "category": "Beverage", "unit": "BTL", "standard_price": 380.0, "vendor": "SUBHAM INTERNATIONAL", "hsn_code": "20089990", "gst_rate": 12.0},
    {"name": "Pomegranate Molasses", "category": "Beverage", "unit": "BTL", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "21069099", "gst_rate": 18.0},
    {"name": "Tamarind Concentrate", "category": "Beverage", "unit": "BTL", "standard_price": 180.0, "vendor": "PRIME FOOD", "hsn_code": "20089990", "gst_rate": 12.0},
    {"name": "Coconut Water 1 L", "category": "Beverage", "unit": "PKT", "standard_price": 95.0, "vendor": "LOTS", "hsn_code": "22029990", "gst_rate": 12.0},
    {"name": "Aloe Vera Juice 1 L", "category": "Beverage", "unit": "BTL", "standard_price": 185.0, "vendor": "LOTS", "hsn_code": "22029990", "gst_rate": 12.0},
    {"name": "Cranberry Juice 1 L", "category": "Beverage", "unit": "BTL", "standard_price": 295.0, "vendor": "FOOD MONDE", "hsn_code": "20098990", "gst_rate": 12.0},
    {"name": "Apple Juice 1 L", "category": "Beverage", "unit": "BTL", "standard_price": 145.0, "vendor": "LOTS", "hsn_code": "20097100", "gst_rate": 12.0},
    {"name": "Orange Juice 1 L", "category": "Beverage", "unit": "BTL", "standard_price": 165.0, "vendor": "LOTS", "hsn_code": "20091200", "gst_rate": 12.0},
    {"name": "Pineapple Juice 1 L", "category": "Beverage", "unit": "BTL", "standard_price": 135.0, "vendor": "LOTS", "hsn_code": "20094900", "gst_rate": 12.0},
    {"name": "Grape Juice 1 L", "category": "Beverage", "unit": "BTL", "standard_price": 195.0, "vendor": "LOTS", "hsn_code": "20096100", "gst_rate": 12.0},
    {"name": "Peach Nectar 1 L", "category": "Beverage", "unit": "BTL", "standard_price": 175.0, "vendor": "FOOD MONDE", "hsn_code": "20098990", "gst_rate": 12.0},
    {"name": "Apricot Nectar 1 L", "category": "Beverage", "unit": "BTL", "standard_price": 185.0, "vendor": "FOOD MONDE", "hsn_code": "20098990", "gst_rate": 12.0},
    {"name": "Monin Vanilla Syrup", "category": "Beverage", "unit": "BTL", "standard_price": 420.0, "vendor": "SUBHAM INTERNATIONAL", "hsn_code": "21069092", "gst_rate": 5.0},
    {"name": "Monin Caramel Syrup", "category": "Beverage", "unit": "BTL", "standard_price": 420.0, "vendor": "SUBHAM INTERNATIONAL", "hsn_code": "21069092", "gst_rate": 5.0},
    {"name": "Monin Hazelnut Syrup", "category": "Beverage", "unit": "BTL", "standard_price": 450.0, "vendor": "SUBHAM INTERNATIONAL", "hsn_code": "21069092", "gst_rate": 5.0},
    {"name": "Monin Strawberry Syrup", "category": "Beverage", "unit": "BTL", "standard_price": 420.0, "vendor": "SUBHAM INTERNATIONAL", "hsn_code": "21069092", "gst_rate": 5.0},
    {"name": "Monin Mango Syrup", "category": "Beverage", "unit": "BTL", "standard_price": 420.0, "vendor": "SUBHAM INTERNATIONAL", "hsn_code": "21069092", "gst_rate": 5.0},
    {"name": "Monin Coconut Syrup", "category": "Beverage", "unit": "BTL", "standard_price": 450.0, "vendor": "SUBHAM INTERNATIONAL", "hsn_code": "21069092", "gst_rate": 5.0},
    {"name": "Monin Passion Fruit Syrup", "category": "Beverage", "unit": "BTL", "standard_price": 480.0, "vendor": "SUBHAM INTERNATIONAL", "hsn_code": "21069092", "gst_rate": 5.0},
    {"name": "Monin Peach Syrup", "category": "Beverage", "unit": "BTL", "standard_price": 420.0, "vendor": "SUBHAM INTERNATIONAL", "hsn_code": "21069092", "gst_rate": 5.0},
    
    # More Non-Veg items
    {"name": "Chicken Thigh Boneless", "category": "Non Veg", "unit": "KG", "standard_price": 320.0, "vendor": "HYPEPURE", "gst_rate": 0},
    {"name": "Chicken Drumstick", "category": "Non Veg", "unit": "KG", "standard_price": 260.0, "vendor": "VIJAY CHICKEN", "gst_rate": 0},
    {"name": "Chicken Mince", "category": "Non Veg", "unit": "KG", "standard_price": 240.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Chicken Sausage", "category": "Non Veg", "unit": "PKT", "standard_price": 245.0, "vendor": "HYPEPURE", "gst_rate": 5.0},
    {"name": "Chicken Frankfurter", "category": "Non Veg", "unit": "PKT", "standard_price": 265.0, "vendor": "HYPEPURE", "gst_rate": 5.0},
    {"name": "Chicken Salami", "category": "Non Veg", "unit": "PKT", "standard_price": 320.0, "vendor": "HYPEPURE", "gst_rate": 5.0},
    {"name": "Lamb Chops", "category": "Non Veg", "unit": "KG", "standard_price": 950.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Lamb Shoulder", "category": "Non Veg", "unit": "KG", "standard_price": 720.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Lamb Shank", "category": "Non Veg", "unit": "KG", "standard_price": 680.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Goat Leg", "category": "Non Veg", "unit": "KG", "standard_price": 850.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Goat Ribs", "category": "Non Veg", "unit": "KG", "standard_price": 580.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Goat Brain", "category": "Non Veg", "unit": "KG", "standard_price": 450.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Goat Liver", "category": "Non Veg", "unit": "KG", "standard_price": 380.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Goat Kidney", "category": "Non Veg", "unit": "KG", "standard_price": 350.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Pork Belly", "category": "Non Veg", "unit": "KG", "standard_price": 520.0, "vendor": "HYPEPURE", "gst_rate": 0},
    {"name": "Pork Ribs", "category": "Non Veg", "unit": "KG", "standard_price": 480.0, "vendor": "HYPEPURE", "gst_rate": 0},
    {"name": "Pork Chops", "category": "Non Veg", "unit": "KG", "standard_price": 550.0, "vendor": "HYPEPURE", "gst_rate": 0},
    {"name": "Pork Tenderloin", "category": "Non Veg", "unit": "KG", "standard_price": 680.0, "vendor": "HYPEPURE", "gst_rate": 0},
    {"name": "Pork Shoulder", "category": "Non Veg", "unit": "KG", "standard_price": 420.0, "vendor": "HYPEPURE", "gst_rate": 0},
    {"name": "Chorizo Sausage", "category": "Non Veg", "unit": "PKT", "standard_price": 480.0, "vendor": "HYPEPURE", "gst_rate": 5.0},
    {"name": "Italian Sausage", "category": "Non Veg", "unit": "PKT", "standard_price": 420.0, "vendor": "HYPEPURE", "gst_rate": 5.0},
    {"name": "Bratwurst", "category": "Non Veg", "unit": "PKT", "standard_price": 450.0, "vendor": "HYPEPURE", "gst_rate": 5.0},
    {"name": "Prosciutto", "category": "Non Veg", "unit": "PKT", "standard_price": 850.0, "vendor": "HYPEPURE", "gst_rate": 5.0},
    {"name": "Pancetta", "category": "Non Veg", "unit": "PKT", "standard_price": 680.0, "vendor": "HYPEPURE", "gst_rate": 5.0},
    
    # More Seafood
    {"name": "Fish Sole", "category": "Seafood", "unit": "KG", "standard_price": 750.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Fish Sea Bass", "category": "Seafood", "unit": "KG", "standard_price": 1100.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Fish Red Snapper", "category": "Seafood", "unit": "KG", "standard_price": 950.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Fish Tilapia", "category": "Seafood", "unit": "KG", "standard_price": 320.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Fish Mackerel", "category": "Seafood", "unit": "KG", "standard_price": 280.0, "vendor": "JP FOOD", "gst_rate": 0},
    {"name": "Fish Sardine", "category": "Seafood", "unit": "KG", "standard_price": 180.0, "vendor": "JP FOOD", "gst_rate": 0},
    {"name": "Fish Anchovy Fresh", "category": "Seafood", "unit": "KG", "standard_price": 320.0, "vendor": "JP FOOD", "gst_rate": 0},
    {"name": "Fish Tuna Steak", "category": "Seafood", "unit": "KG", "standard_price": 1800.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Shrimp Large", "category": "Seafood", "unit": "KG", "standard_price": 850.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Shrimp Small", "category": "Seafood", "unit": "KG", "standard_price": 480.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Calamari Rings", "category": "Seafood", "unit": "KG", "standard_price": 580.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Octopus Tentacles", "category": "Seafood", "unit": "KG", "standard_price": 1100.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Cuttlefish", "category": "Seafood", "unit": "KG", "standard_price": 420.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Eel Fresh", "category": "Seafood", "unit": "KG", "standard_price": 1200.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Caviar 50 G", "category": "Seafood", "unit": "JAR", "standard_price": 4500.0, "vendor": "FOOD MONDE", "gst_rate": 18.0},
    {"name": "Fish Roe Tobiko", "category": "Seafood", "unit": "PKT", "standard_price": 850.0, "vendor": "FOOD MONDE", "gst_rate": 18.0},
    {"name": "Fish Roe Masago", "category": "Seafood", "unit": "PKT", "standard_price": 650.0, "vendor": "FOOD MONDE", "gst_rate": 18.0},
    {"name": "Smoked Salmon", "category": "Seafood", "unit": "PKT", "standard_price": 950.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    
    # More Dairy
    {"name": "Blue Cheese", "category": "Dairy Product", "unit": "KG", "standard_price": 1450.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Gouda Cheese", "category": "Dairy Product", "unit": "KG", "standard_price": 950.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Brie Cheese", "category": "Dairy Product", "unit": "KG", "standard_price": 1200.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Camembert Cheese", "category": "Dairy Product", "unit": "KG", "standard_price": 1300.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Gruyere Cheese", "category": "Dairy Product", "unit": "KG", "standard_price": 1550.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Emmental Cheese", "category": "Dairy Product", "unit": "KG", "standard_price": 1100.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Pecorino Romano", "category": "Dairy Product", "unit": "KG", "standard_price": 1650.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Halloumi Cheese", "category": "Dairy Product", "unit": "KG", "standard_price": 1250.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Burrata", "category": "Dairy Product", "unit": "PCS", "standard_price": 450.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Buffalo Mozzarella", "category": "Dairy Product", "unit": "KG", "standard_price": 1350.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Sour Cream 200 G", "category": "Dairy Product", "unit": "TUB", "standard_price": 145.0, "vendor": "YASH DAIRY", "gst_rate": 5.0},
    {"name": "Creme Fraiche 200 G", "category": "Dairy Product", "unit": "TUB", "standard_price": 185.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Clotted Cream 200 G", "category": "Dairy Product", "unit": "TUB", "standard_price": 320.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Double Cream 500 ML", "category": "Dairy Product", "unit": "PKT", "standard_price": 280.0, "vendor": "YASH DAIRY", "gst_rate": 5.0},
    {"name": "Single Cream 500 ML", "category": "Dairy Product", "unit": "PKT", "standard_price": 180.0, "vendor": "YASH DAIRY", "gst_rate": 5.0},
    {"name": "Labneh 500 G", "category": "Dairy Product", "unit": "TUB", "standard_price": 280.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Kefir 500 ML", "category": "Dairy Product", "unit": "BTL", "standard_price": 165.0, "vendor": "YASH DAIRY", "gst_rate": 5.0},
    
    # More Continental/European
    {"name": "Pesto Basil 190 G", "category": "Continental Grocery", "unit": "JAR", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Pesto Red 190 G", "category": "Continental Grocery", "unit": "JAR", "standard_price": 340.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Tapenade Olive", "category": "Continental Grocery", "unit": "JAR", "standard_price": 380.0, "vendor": "FOOD MONDE", "hsn_code": "20059900", "gst_rate": 5.0},
    {"name": "Hummus 200 G", "category": "Continental Grocery", "unit": "TUB", "standard_price": 180.0, "vendor": "FOOD MONDE", "hsn_code": "20055900", "gst_rate": 5.0},
    {"name": "Tahini Paste", "category": "Continental Grocery", "unit": "JAR", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "20081910", "gst_rate": 5.0},
    {"name": "Harissa Paste", "category": "Continental Grocery", "unit": "JAR", "standard_price": 285.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Ras El Hanout", "category": "Continental Grocery", "unit": "PKT", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Dukkah Spice", "category": "Continental Grocery", "unit": "PKT", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Za'atar Spice", "category": "Continental Grocery", "unit": "PKT", "standard_price": 245.0, "vendor": "FOOD MONDE", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Sumac Spice", "category": "Continental Grocery", "unit": "PKT", "standard_price": 220.0, "vendor": "FOOD MONDE", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Preserved Lemon", "category": "Continental Grocery", "unit": "JAR", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "20089990", "gst_rate": 5.0},
    {"name": "Sundried Tomato", "category": "Continental Grocery", "unit": "JAR", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "20029090", "gst_rate": 5.0},
    {"name": "Roasted Red Pepper", "category": "Continental Grocery", "unit": "JAR", "standard_price": 285.0, "vendor": "FOOD MONDE", "hsn_code": "20059900", "gst_rate": 5.0},
    {"name": "Marinated Artichoke", "category": "Continental Grocery", "unit": "JAR", "standard_price": 350.0, "vendor": "FOOD MONDE", "hsn_code": "20059900", "gst_rate": 5.0},
    {"name": "Anchovy Fillet", "category": "Continental Grocery", "unit": "CAN", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "16041300", "gst_rate": 5.0},
    {"name": "Truffle Oil 100 ML", "category": "Continental Grocery", "unit": "BTL", "standard_price": 650.0, "vendor": "FOOD MONDE", "hsn_code": "15099090", "gst_rate": 5.0},
    {"name": "White Truffle Paste", "category": "Continental Grocery", "unit": "JAR", "standard_price": 1200.0, "vendor": "FOOD MONDE", "hsn_code": "20039090", "gst_rate": 5.0},
    {"name": "Black Truffle Paste", "category": "Continental Grocery", "unit": "JAR", "standard_price": 1100.0, "vendor": "FOOD MONDE", "hsn_code": "20039090", "gst_rate": 5.0},
    
    # Fruits
    {"name": "Apple Red", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 180.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Apple Green", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 200.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Orange", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 80.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Kiwi", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 280.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Strawberry", "category": "Fruits & Vegetables", "unit": "PKT", "standard_price": 180.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Raspberry", "category": "Fruits & Vegetables", "unit": "PKT", "standard_price": 450.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Blackberry", "category": "Fruits & Vegetables", "unit": "PKT", "standard_price": 420.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Cranberry Fresh", "category": "Fruits & Vegetables", "unit": "PKT", "standard_price": 380.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Grapes Green", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 120.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Grapes Black", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 140.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Mango Alphonso", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 450.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Mango Totapuri", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 80.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Papaya Ripe", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 50.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Watermelon", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 25.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Muskmelon", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 40.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Honeydew Melon", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 80.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Dragon Fruit", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 350.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Passion Fruit", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 320.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Lychee", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 180.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Longan", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 250.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Rambutan", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 380.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Mangosteen", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 650.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Jackfruit", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 80.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Durian", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 850.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Fig Fresh", "category": "Fruits & Vegetables", "unit": "PKT", "standard_price": 320.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Date Fresh", "category": "Fruits & Vegetables", "unit": "PKT", "standard_price": 280.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Plum", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 180.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Peach Fresh", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 220.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Apricot Fresh", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 280.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Cherry Fresh", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 650.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Pear", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 180.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Avocado", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 380.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Coconut Tender", "category": "Fruits & Vegetables", "unit": "PCS", "standard_price": 45.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
]

print(f"Additional items count: {len(MORE_ITEMS)}")
