#!/usr/bin/env python3
"""
DREAMOVEN Inventory System - Data Seeding Script
Seeds: Admin user, 15 kitchens, categories, vendors, and items
"""

import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime, timezone
import uuid
import bcrypt
import os
from dotenv import load_dotenv
from pathlib import Path

ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / '.env')

mongo_url = os.environ['MONGO_URL']
db_name = os.environ['DB_NAME']

# Kitchen data
KITCHENS = [
    {"name": "Main Store", "code": "MAIN", "is_main_store": True},
    {"name": "Sticky Rice PB", "code": "SRPB", "is_main_store": False},
    {"name": "Kalaunji PB", "code": "KLPB", "is_main_store": False},
    {"name": "Coimbatore", "code": "CMBR", "is_main_store": False},
    {"name": "Aioli", "code": "AIOL", "is_main_store": False},
    {"name": "DO Cafe", "code": "DOCF", "is_main_store": False},
    {"name": "DO Bakery", "code": "DOBK", "is_main_store": False},
    {"name": "DO GCR", "code": "DGCR", "is_main_store": False},
    {"name": "DO Munirika", "code": "DMUN", "is_main_store": False},
    {"name": "Dashi PB", "code": "DSPB", "is_main_store": False},
    {"name": "Dashi MT", "code": "DSMT", "is_main_store": False},
    {"name": "Dashi RN", "code": "DSRN", "is_main_store": False},
    {"name": "Sticky Rice DFC", "code": "SRDF", "is_main_store": False},
    {"name": "Sticky Rice NFC", "code": "SRNF", "is_main_store": False},
    {"name": "Sticky Rice Noida", "code": "SRND", "is_main_store": False},
]

# Categories
CATEGORIES = [
    "Packaging", "Continental Grocery", "Vegetables", "Beverage", "Chinese Grocery",
    "Indian Grocery", "Dairy", "Non Veg", "Housekeeping", "Seafood", "Bakery", 
    "Fruits & Vegetables", "Dairy Product", "Seasoning"
]

# Vendors from Excel data
VENDORS = [
    {"name": "ECOTEGRITY", "supply_categories": ["Packaging"]},
    {"name": "FOOD MONDE", "supply_categories": ["Continental Grocery", "Chinese Grocery", "Dairy Product"]},
    {"name": "PRIME FOOD", "supply_categories": ["Vegetables", "Indian Grocery"]},
    {"name": "VDEV TRADERS", "supply_categories": ["Vegetables"]},
    {"name": "SUBHAM INTERNATIONAL", "supply_categories": ["Beverage"]},
    {"name": "PACKADGE", "supply_categories": ["Packaging"]},
    {"name": "LOTS", "supply_categories": ["Indian Grocery", "Beverage", "Housekeeping"]},
    {"name": "TIRUPATI", "supply_categories": ["Indian Grocery"]},
    {"name": "NGK RETAIL", "supply_categories": ["Vegetables"]},
    {"name": "EASY SHOP MARKETING", "supply_categories": ["Packaging"]},
    {"name": "Y K TRADERS", "supply_categories": ["Continental Grocery", "Chinese Grocery"]},
    {"name": "HYPEPURE", "supply_categories": ["Non Veg", "Seafood"]},
    {"name": "J P FOOD", "supply_categories": ["Non Veg"]},
    {"name": "VIJAY CHICKEN", "supply_categories": ["Non Veg"]},
    {"name": "SHREEJEE", "supply_categories": ["Packaging", "Housekeeping"]},
    {"name": "DREAM OVEN", "supply_categories": ["Dairy", "Bakery"]},
    {"name": "SUDH GARHWAL", "supply_categories": ["Dairy"]},
    {"name": "KISHAN BHANDAR", "supply_categories": ["Dairy"]},
    {"name": "RJ TRINATH", "supply_categories": ["Seafood"]},
    {"name": "EURO FOODS", "supply_categories": ["Continental Grocery"]},
    {"name": "RAKESH VEGETABLE", "supply_categories": ["Fruits & Vegetables"]},
    {"name": "BIOSYS INDIA", "supply_categories": ["Vegetables"]},
    {"name": "BEETA TISSUE", "supply_categories": ["Packaging"]},
    {"name": "KRISHNA RIBON", "supply_categories": ["Packaging"]},
    {"name": "CUP KONE", "supply_categories": ["Packaging"]},
    {"name": "HYPERPURE", "supply_categories": ["Non Veg", "Packaging"]},
    {"name": "BABU RAM", "supply_categories": ["Chinese Grocery"]},
    {"name": "CP", "supply_categories": ["Indian Grocery", "Beverage"]},
    {"name": "VIPIN & V DEV", "supply_categories": ["Vegetables"]},
    {"name": "YASH DAIRY", "supply_categories": ["Dairy Product"]},
    {"name": "MK HOSPITALITY", "supply_categories": ["Seafood"]},
    {"name": "PL ENTERPRISES", "supply_categories": ["Dairy Product"]},
    {"name": "HONEY PRINTER", "supply_categories": ["Packaging"]},
    {"name": "INSTAPACK ENTERPRISE", "supply_categories": ["Indian Grocery"]},
    {"name": "POLYWRAP INDIA", "supply_categories": ["Packaging"]},
    {"name": "KAPOOR ENTERPRISES", "supply_categories": ["Beverage"]},
    {"name": "AZOIC WATER PVT LTD", "supply_categories": ["Beverage"]},
    {"name": "EASYSHOP MARKETING PVT LTD", "supply_categories": ["Packaging"]},
    {"name": "LALIT AGGARWAL NOODLES", "supply_categories": ["Chinese Grocery"]},
    {"name": "SELICO PLASTICS", "supply_categories": ["Packaging"]},
    {"name": "HONETPRINTER", "supply_categories": ["Packaging"]},
    {"name": "PACKEDGE", "supply_categories": ["Packaging"]},
    {"name": "PRIME FOODS", "supply_categories": ["Indian Grocery"]},
    {"name": "SHREE JEE ENTERPRISES", "supply_categories": ["Housekeeping"]},
    {"name": "Y K TRADING COMPANY", "supply_categories": ["Chinese Grocery"]},
    {"name": "JP FOOD", "supply_categories": ["Non Veg", "Seafood"]},
    {"name": "VIJAY & JP FOOD", "supply_categories": ["Non Veg"]},
]

# Items - Comprehensive list from Excel data (cleaned and valid items only)
ITEMS = [
    {"name": "Tissue white 300x300 2ply", "category": "Packaging", "unit": "PKT", "standard_price": 23.0, "vendor": "ECOTEGRITY", "hsn_code": "4807", "gst_rate": 18.0},
    {"name": "Wooden chopsticks 21cm", "category": "Packaging", "unit": "PKT", "standard_price": 1.2, "vendor": "ECOTEGRITY", "hsn_code": "4421", "gst_rate": 5.0},
    {"name": "Abbie's American Yellow Mustard Sauce 255G", "category": "Continental Grocery", "unit": "BTL", "standard_price": 151.3, "vendor": "FOOD MONDE", "hsn_code": "21033000", "gst_rate": 5.0},
    {"name": "Achari Mirch", "category": "Vegetables", "unit": "KG", "standard_price": 100.0, "vendor": "VIPIN & V DEV", "gst_rate": 0},
    {"name": "Ad Flower", "category": "Vegetables", "unit": "KG", "standard_price": 270.0, "vendor": "VIPIN & V DEV", "gst_rate": 0},
    {"name": "Agave Syrup", "category": "Beverage", "unit": "BTL", "standard_price": 703.5, "vendor": "SUBHAM INTERNATIONAL", "hsn_code": "21069092", "gst_rate": 5.0},
    {"name": "Aioli Bag", "category": "Continental Grocery", "unit": "PCS", "standard_price": None, "vendor": "PACKADGE", "gst_rate": 0},
    {"name": "All Spice Ground 400 GRM", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 787.5, "vendor": "FOOD MONDE", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Amchur Powder", "category": "Indian Grocery", "unit": "PKT", "standard_price": 65.0, "vendor": "LOTS", "hsn_code": "9109929", "gst_rate": 5.0},
    {"name": "Amul Cheese Tin", "category": "Indian Grocery", "unit": "PCS", "standard_price": 244.16, "vendor": "FOOD MONDE", "hsn_code": "406", "gst_rate": 5.0},
    {"name": "Amul Ghee 1L", "category": "Indian Grocery", "unit": "PCS", "standard_price": 580.0, "vendor": "LOTS", "hsn_code": "40590", "gst_rate": 5.0},
    {"name": "Amul Chiplet", "category": "Dairy", "unit": "PKT", "standard_price": 694.4, "vendor": "FOOD MONDE", "hsn_code": "405", "gst_rate": 5.0},
    {"name": "Anardana", "category": "Indian Grocery", "unit": "PKT", "standard_price": 120.0, "vendor": "PRIME FOOD", "hsn_code": "081110", "gst_rate": 0},
    {"name": "Arbi", "category": "Vegetables", "unit": "KG", "standard_price": 60.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Arabic 7 Spice Powder 400 GRM", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 498.75, "vendor": "FOOD MONDE", "hsn_code": "9109100", "gst_rate": 5.0},
    {"name": "Arborio Rice Scotti 1 KG", "category": "Chinese Grocery", "unit": "KG", "standard_price": 414.75, "vendor": "FOOD MONDE", "hsn_code": "10063090", "gst_rate": 5.0},
    {"name": "Artichoke Hearts 390 GRM", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 204.75, "vendor": "FOOD MONDE", "hsn_code": "20059900", "gst_rate": 5.0},
    {"name": "Asparagus", "category": "Vegetables", "unit": "KG", "standard_price": 600.0, "vendor": "NGK RETAIL", "gst_rate": 0},
    {"name": "Atta 10 KG", "category": "Indian Grocery", "unit": "BAG", "standard_price": 6739.7, "vendor": "LOTS", "hsn_code": "11010000", "gst_rate": 5.0},
    {"name": "Almond", "category": "Indian Grocery", "unit": "KG", "standard_price": 865.0, "vendor": "PRIME FOOD", "hsn_code": "080132", "gst_rate": 5.0},
    {"name": "Apple Cider Vinegar", "category": "Indian Grocery", "unit": "PCS", "standard_price": 350.0, "vendor": "LOTS", "hsn_code": "17011490", "gst_rate": 5.0},
    {"name": "Aromat Seasoning", "category": "Continental Grocery", "unit": "PKT", "standard_price": 180.0, "vendor": "Y K TRADERS", "gst_rate": 5.0},
    {"name": "Baby Corn", "category": "Vegetables", "unit": "KG", "standard_price": 110.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Baby Pochoy", "category": "Vegetables", "unit": "KG", "standard_price": 160.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Badi Elaichi", "category": "Indian Grocery", "unit": "PKT", "standard_price": 350.0, "vendor": "PRIME FOOD", "hsn_code": "90921", "gst_rate": 5.0},
    {"name": "Baking Powder", "category": "Indian Grocery", "unit": "PCS", "standard_price": 78.75, "vendor": "FOOD MONDE", "hsn_code": "2102300", "gst_rate": 5.0},
    {"name": "Balsamic Glaze", "category": "Continental Grocery", "unit": "BTL", "standard_price": 295.0, "vendor": "FOOD MONDE", "hsn_code": "22090090", "gst_rate": 18.0},
    {"name": "Balsamic Vinegar", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "22090090", "gst_rate": 18.0},
    {"name": "Bambino Vermicelli 850 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 174.24, "vendor": "TIRUPATI", "hsn_code": "19021900", "gst_rate": 5.0},
    {"name": "Bamboo Shoot 560 GRM", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 90.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Banana", "category": "Vegetables", "unit": "KG", "standard_price": 6.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Banana Leaves", "category": "Vegetables", "unit": "PCS", "standard_price": 20.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Barcode Label", "category": "Packaging", "unit": "PCS", "standard_price": 236.0, "vendor": "EASY SHOP MARKETING", "hsn_code": "48219010", "gst_rate": 18.0},
    {"name": "Bathua", "category": "Vegetables", "unit": "KG", "standard_price": 60.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Bay Leaves", "category": "Indian Grocery", "unit": "PKT", "standard_price": 45.0, "vendor": "PRIME FOOD", "hsn_code": "0910", "gst_rate": 0},
    {"name": "BBQ Sauce 510 GRM", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 183.75, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Beans Sprouts", "category": "Vegetables", "unit": "KG", "standard_price": 130.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Beetroot", "category": "Vegetables", "unit": "KG", "standard_price": 30.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Basil", "category": "Vegetables", "unit": "KG", "standard_price": 100.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Betki Fish", "category": "Non Veg", "unit": "KG", "standard_price": 650.0, "vendor": "HYPEPURE", "gst_rate": 0},
    {"name": "Big Sole Fish", "category": "Non Veg", "unit": "KG", "standard_price": 1215.0, "vendor": "HYPEPURE", "gst_rate": 0},
    {"name": "Bisleri Soda 750 ML", "category": "Beverage", "unit": "BTL", "standard_price": 129.6, "vendor": "LOTS", "hsn_code": "220110", "gst_rate": 5.0},
    {"name": "Black Bean Preserved 500 GRM", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 183.75, "vendor": "FOOD MONDE", "hsn_code": "20055900", "gst_rate": 5.0},
    {"name": "Black Fungus Dried 1 KG", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 682.5, "vendor": "FOOD MONDE", "hsn_code": "20039090", "gst_rate": 5.0},
    {"name": "Black Mushroom Shiitake", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 945.0, "vendor": "FOOD MONDE", "hsn_code": "20031000", "gst_rate": 5.0},
    {"name": "Blueberry", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 800.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Bouffant Cap (Chef Cap)", "category": "Packaging", "unit": "PCS", "standard_price": 15.85, "vendor": "SHREEJEE", "hsn_code": "65050090", "gst_rate": 5.0},
    {"name": "Bread White", "category": "Dairy", "unit": "PCS", "standard_price": 60.0, "vendor": "DREAM OVEN", "hsn_code": "1905", "gst_rate": 0},
    {"name": "Bread Crumb Panko 1 KG", "category": "Chinese Grocery", "unit": "KG", "standard_price": 110.25, "vendor": "FOOD MONDE", "hsn_code": "19059090", "gst_rate": 5.0},
    {"name": "Breast Boneless Chicken", "category": "Non Veg", "unit": "KG", "standard_price": 280.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Brinjal", "category": "Vegetables", "unit": "KG", "standard_price": 30.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Broccoli", "category": "Vegetables", "unit": "KG", "standard_price": 160.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Brown Bread", "category": "Dairy", "unit": "PCS", "standard_price": 55.0, "vendor": "DREAM OVEN", "hsn_code": "1905", "gst_rate": 0},
    {"name": "Brown Sugar 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 85.0, "vendor": "PRIME FOOD", "hsn_code": "7132000", "gst_rate": 5.0},
    {"name": "Bush Vanilla Extract", "category": "Continental Grocery", "unit": "BTL", "standard_price": 180.0, "vendor": "EURO FOODS", "gst_rate": 5.0},
    {"name": "Butter Unsalted", "category": "Dairy", "unit": "KG", "standard_price": 604.8, "vendor": "SUDH GARHWAL", "hsn_code": "405", "gst_rate": 5.0},
    {"name": "Black Salt 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 77.0, "vendor": "PRIME FOOD", "hsn_code": "25010010", "gst_rate": 0},
    {"name": "Blueberry Monin Syrup", "category": "Beverage", "unit": "BTL", "standard_price": 450.0, "vendor": "SUBHAM INTERNATIONAL", "hsn_code": "21069092", "gst_rate": 5.0},
    {"name": "Cabbage", "category": "Vegetables", "unit": "KG", "standard_price": 28.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Cajun Seasoning", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 399.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Capers 100 ML", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 89.25, "vendor": "FOOD MONDE", "hsn_code": "20059900", "gst_rate": 5.0},
    {"name": "Capsicum Green", "category": "Vegetables", "unit": "KG", "standard_price": 58.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Capsicum Yellow", "category": "Vegetables", "unit": "KG", "standard_price": 160.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Cardamom Green", "category": "Indian Grocery", "unit": "PKT", "standard_price": 1200.0, "vendor": "PRIME FOOD", "hsn_code": "0908", "gst_rate": 0},
    {"name": "Carrot", "category": "Vegetables", "unit": "KG", "standard_price": 30.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Cashew", "category": "Indian Grocery", "unit": "KG", "standard_price": 865.0, "vendor": "PRIME FOOD", "hsn_code": "080132", "gst_rate": 5.0},
    {"name": "Catch Club Soda 500 ML", "category": "Beverage", "unit": "CAN", "standard_price": 363.36, "vendor": "LOTS", "hsn_code": "22011020", "gst_rate": 5.0},
    {"name": "Cauliflower", "category": "Vegetables", "unit": "KG", "standard_price": 55.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Chaap Soya", "category": "Dairy", "unit": "KG", "standard_price": 99.75, "vendor": "KISHAN BHANDAR", "hsn_code": "1201", "gst_rate": 5.0},
    {"name": "Chef Choice Pad Thai Sauce 150 ML", "category": "Chinese Grocery", "unit": "ML", "standard_price": 120.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Cherry Tomato", "category": "Vegetables", "unit": "KG", "standard_price": 160.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Chicken Bones", "category": "Non Veg", "unit": "KG", "standard_price": 80.0, "vendor": "VIJAY CHICKEN", "gst_rate": 0},
    {"name": "Chicken Feet", "category": "Non Veg", "unit": "KG", "standard_price": 100.0, "vendor": "VIJAY CHICKEN", "gst_rate": 0},
    {"name": "Chicken Kalmi", "category": "Non Veg", "unit": "KG", "standard_price": 275.0, "vendor": "HYPEPURE", "gst_rate": 0},
    {"name": "Chicken Keema", "category": "Non Veg", "unit": "KG", "standard_price": 220.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Chicken Seasoning 800 GRM", "category": "Continental Grocery", "unit": "PCS", "standard_price": 210.0, "vendor": "Y K TRADERS", "gst_rate": 5.0},
    {"name": "Chicken Tandoori Whole", "category": "Non Veg", "unit": "PCS", "standard_price": 160.0, "vendor": "VIJAY CHICKEN", "gst_rate": 0},
    {"name": "Chicken Whole", "category": "Non Veg", "unit": "KG", "standard_price": 220.0, "vendor": "VIJAY CHICKEN", "gst_rate": 0},
    {"name": "Chicken Wings", "category": "Non Veg", "unit": "KG", "standard_price": 275.0, "vendor": "VIJAY CHICKEN", "gst_rate": 0},
    {"name": "Chilli Flakes 1 KG", "category": "Chinese Grocery", "unit": "KG", "standard_price": 304.5, "vendor": "FOOD MONDE", "hsn_code": "9042211", "gst_rate": 5.0},
    {"name": "Chilli Green", "category": "Vegetables", "unit": "KG", "standard_price": 45.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "China Cabbage", "category": "Vegetables", "unit": "KG", "standard_price": 100.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "China Cucumber", "category": "Vegetables", "unit": "KG", "standard_price": 50.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Chinkiang Vinegar", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 153.4, "vendor": "FOOD MONDE", "hsn_code": "22090090", "gst_rate": 18.0},
    {"name": "Chipotle Pepper", "category": "Continental Grocery", "unit": "PCS", "standard_price": 280.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Chunky Peanut Butter", "category": "Indian Grocery", "unit": "PKT", "standard_price": 320.0, "vendor": "LOTS", "hsn_code": "9109100", "gst_rate": 5.0},
    {"name": "Cling Film PVC 1.400", "category": "Housekeeping", "unit": "PCS", "standard_price": 198.24, "vendor": "SHREEJEE", "hsn_code": "39204300", "gst_rate": 18.0},
    {"name": "Cloves 50 GM", "category": "Indian Grocery", "unit": "PKT", "standard_price": 85.0, "vendor": "PRIME FOOD", "hsn_code": "907", "gst_rate": 5.0},
    {"name": "Coca Cola Can 300 ML", "category": "Beverage", "unit": "CAN", "standard_price": 28.17, "vendor": "LOTS", "hsn_code": "22021010", "gst_rate": 40.0},
    {"name": "Coconut", "category": "Vegetables", "unit": "PCS", "standard_price": 60.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Colin Glass Cleaner 500 ML", "category": "Housekeeping", "unit": "ML", "standard_price": 192.96, "vendor": "LOTS", "hsn_code": "34022090", "gst_rate": 18.0},
    {"name": "Cooking Sauce Maggie", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 157.5, "vendor": "FOOD MONDE", "hsn_code": "21039040", "gst_rate": 5.0},
    {"name": "Cooking Sauce Kikoman", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 341.25, "vendor": "FOOD MONDE", "hsn_code": "21039040", "gst_rate": 5.0},
    {"name": "Cooking Sake 1.8 LTR", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 525.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Cooking Wine China Huatua", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 110.25, "vendor": "FOOD MONDE", "hsn_code": "21039040", "gst_rate": 5.0},
    {"name": "Cardamom Big", "category": "Indian Grocery", "unit": "PKT", "standard_price": 520.0, "vendor": "PRIME FOOD", "hsn_code": "908", "gst_rate": 0},
    {"name": "Coriander Fresh", "category": "Vegetables", "unit": "KG", "standard_price": 80.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Cornitos Green Peas Wasabi", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 120.75, "vendor": "FOOD MONDE", "hsn_code": "21069099", "gst_rate": 5.0},
    {"name": "Crab Stick", "category": "Seafood", "unit": "PCS", "standard_price": 260.0, "vendor": "RJ TRINATH", "hsn_code": "16042000", "gst_rate": 5.0},
    {"name": "Cracker Monora 500 GRM", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 341.25, "vendor": "FOOD MONDE", "hsn_code": "19054000", "gst_rate": 5.0},
    {"name": "Cream Cheese Dlecta 1 KG", "category": "Dairy Product", "unit": "PCS", "standard_price": 665.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Cucumber", "category": "Vegetables", "unit": "KG", "standard_price": 32.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Cassia Cinnamon", "category": "Indian Grocery", "unit": "PKT", "standard_price": 125.0, "vendor": "PRIME FOOD", "hsn_code": "960", "gst_rate": 5.0},
    {"name": "Caustic Soda", "category": "Housekeeping", "unit": "KG", "standard_price": 112.1, "vendor": "SHREEJEE", "gst_rate": 18.0},
    {"name": "Cheddar Red Block", "category": "Dairy", "unit": "KG", "standard_price": 866.25, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Chilli Sachet", "category": "Continental Grocery", "unit": "PKT", "standard_price": 35.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Chukde Saffron 500 MG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 139.1, "vendor": "LOTS", "gst_rate": 5.0},
    {"name": "Classic Corn Flour 25 KG", "category": "Indian Grocery", "unit": "BAG", "standard_price": 1333.0, "vendor": "LOTS", "hsn_code": "11081200", "gst_rate": 5.0},
    {"name": "Coke Zero Can 300 ML", "category": "Beverage", "unit": "CAN", "standard_price": 31.36, "vendor": "LOTS", "gst_rate": 40.0},
    {"name": "Dinner Paper Napkin Black", "category": "Packaging", "unit": "PCS", "standard_price": 125.0, "vendor": "BEETA TISSUE", "hsn_code": "48183000", "gst_rate": 18.0},
    {"name": "Corn Flour 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 65.0, "vendor": "LOTS", "hsn_code": "11081200", "gst_rate": 5.0},
    {"name": "Dabur Rose Water 250 ML", "category": "Indian Grocery", "unit": "BTL", "standard_price": 56.0, "vendor": "PRIME FOOD", "hsn_code": "21069099", "gst_rate": 5.0},
    {"name": "Dabur Honey 1 KG", "category": "Indian Grocery", "unit": "KG", "standard_price": 376.2, "vendor": "LOTS", "hsn_code": "4090000", "gst_rate": 5.0},
    {"name": "Dabur Kewara Water 250 ML", "category": "Indian Grocery", "unit": "BTL", "standard_price": 75.0, "vendor": "PRIME FOOD", "hsn_code": "3303", "gst_rate": 18.0},
    {"name": "Daffodil M-Fold Napkin", "category": "Housekeeping", "unit": "PCS", "standard_price": 45.0, "vendor": "LOTS", "hsn_code": "48182000", "gst_rate": 18.0},
    {"name": "Dahi Fresh", "category": "Dairy Product", "unit": "KG", "standard_price": 67.2, "vendor": "KISHAN BHANDAR", "hsn_code": "403", "gst_rate": 5.0},
    {"name": "Dal Masoor 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 87.0, "vendor": "PRIME FOOD", "hsn_code": "713", "gst_rate": 0},
    {"name": "Dal Moong 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 145.0, "vendor": "PRIME FOOD", "hsn_code": "713", "gst_rate": 0},
    {"name": "Dal Toor 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 165.0, "vendor": "PRIME FOOD", "hsn_code": "713", "gst_rate": 0},
    {"name": "Dal Urad 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 180.0, "vendor": "PRIME FOOD", "hsn_code": "071320", "gst_rate": 0},
    {"name": "Damati Container 300 ML", "category": "Packaging", "unit": "ML", "standard_price": 2.93, "vendor": "ECOTEGRITY", "hsn_code": "3923", "gst_rate": 18.0},
    {"name": "Damati Round 500 ML", "category": "Packaging", "unit": "PCS", "standard_price": 3.55, "vendor": "ECOTEGRITY", "hsn_code": "3923", "gst_rate": 18.0},
    {"name": "Damati Bowl 650 ML", "category": "Packaging", "unit": "PCS", "standard_price": 5.5, "vendor": "ECOTEGRITY", "hsn_code": "3923", "gst_rate": 18.0},
    {"name": "Damati Cherry 600 ML", "category": "Packaging", "unit": "ML", "standard_price": 7.48, "vendor": "ECOTEGRITY", "hsn_code": "3923", "gst_rate": 18.0},
    {"name": "Damati RO 16", "category": "Packaging", "unit": "PCS", "standard_price": 5.25, "vendor": "ECOTEGRITY", "hsn_code": "3923", "gst_rate": 18.0},
    {"name": "Damati RO 24", "category": "Packaging", "unit": "PCS", "standard_price": 6.8, "vendor": "ECOTEGRITY", "hsn_code": "3923", "gst_rate": 18.0},
    {"name": "Dark Soya Sauce 1.5 LTR LKK", "category": "Chinese Grocery", "unit": "CAN", "standard_price": 3570.0, "vendor": "FOOD MONDE", "hsn_code": "21031000", "gst_rate": 5.0},
    {"name": "Deggi Mirch Powder", "category": "Indian Grocery", "unit": "PKT", "standard_price": 320.0, "vendor": "LOTS", "hsn_code": "9042211", "gst_rate": 5.0},
    {"name": "Demi Glaze Sauce", "category": "Continental Grocery", "unit": "PCS", "standard_price": 380.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Desi Garlic", "category": "Vegetables", "unit": "KG", "standard_price": 160.0, "vendor": "BIOSYS INDIA", "gst_rate": 0},
    {"name": "Dhania Powder 500 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 110.0, "vendor": "LOTS", "hsn_code": "9092200", "gst_rate": 5.0},
    {"name": "Dhania Sabut 500 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 65.0, "vendor": "PRIME FOOD", "hsn_code": "90921", "gst_rate": 5.0},
    {"name": "Dijon Mustard", "category": "Continental Grocery", "unit": "PCS", "standard_price": 220.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Diet Coke Can 300 ML", "category": "Beverage", "unit": "CAN", "standard_price": 28.17, "vendor": "LOTS", "gst_rate": 40.0},
    {"name": "Drumstick", "category": "Vegetables", "unit": "KG", "standard_price": 80.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Egg Tray 30 PCS", "category": "Dairy Product", "unit": "TRAY", "standard_price": 210.0, "vendor": "YASH DAIRY", "gst_rate": 0},
    {"name": "Extra Virgin Olive Oil 1 L", "category": "Continental Grocery", "unit": "BTL", "standard_price": 750.0, "vendor": "FOOD MONDE", "hsn_code": "15091000", "gst_rate": 5.0},
    {"name": "Fennel Seeds 500 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 125.0, "vendor": "PRIME FOOD", "hsn_code": "90921", "gst_rate": 5.0},
    {"name": "Feta Cheese", "category": "Dairy Product", "unit": "KG", "standard_price": 950.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Fish Sauce 700 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 185.0, "vendor": "FOOD MONDE", "hsn_code": "16039090", "gst_rate": 5.0},
    {"name": "French Beans", "category": "Vegetables", "unit": "KG", "standard_price": 80.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Fresh Cream 1 L", "category": "Dairy Product", "unit": "LTR", "standard_price": 220.0, "vendor": "YASH DAIRY", "gst_rate": 5.0},
    {"name": "Garam Masala 500 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 195.0, "vendor": "LOTS", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Garlic Fresh", "category": "Vegetables", "unit": "KG", "standard_price": 120.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Garlic Paste", "category": "Indian Grocery", "unit": "KG", "standard_price": 150.0, "vendor": "PRIME FOOD", "gst_rate": 5.0},
    {"name": "Ghee Amul 1 L", "category": "Dairy Product", "unit": "LTR", "standard_price": 580.0, "vendor": "LOTS", "hsn_code": "40590", "gst_rate": 5.0},
    {"name": "Ginger Fresh", "category": "Vegetables", "unit": "KG", "standard_price": 120.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Ginger Paste", "category": "Indian Grocery", "unit": "KG", "standard_price": 140.0, "vendor": "PRIME FOOD", "gst_rate": 5.0},
    {"name": "Glass Noodles 500 G", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 180.0, "vendor": "FOOD MONDE", "hsn_code": "19021900", "gst_rate": 5.0},
    {"name": "Green Peas Frozen", "category": "Vegetables", "unit": "KG", "standard_price": 120.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Groundnut Oil 15 L", "category": "Indian Grocery", "unit": "TIN", "standard_price": 2800.0, "vendor": "LOTS", "hsn_code": "15081000", "gst_rate": 5.0},
    {"name": "Hakka Noodles 1 KG", "category": "Chinese Grocery", "unit": "KG", "standard_price": 85.0, "vendor": "BABU RAM", "hsn_code": "19021900", "gst_rate": 5.0},
    {"name": "Hoisin Sauce 500 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 295.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Honey Organic 500 G", "category": "Indian Grocery", "unit": "BTL", "standard_price": 280.0, "vendor": "LOTS", "hsn_code": "4090000", "gst_rate": 0},
    {"name": "Ice Cream Vanilla 5 L", "category": "Dairy Product", "unit": "TUB", "standard_price": 750.0, "vendor": "YASH DAIRY", "gst_rate": 5.0},
    {"name": "Italian Herbs Mix", "category": "Continental Grocery", "unit": "PKT", "standard_price": 125.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Jalapeno Sliced", "category": "Continental Grocery", "unit": "JAR", "standard_price": 180.0, "vendor": "FOOD MONDE", "hsn_code": "20059900", "gst_rate": 5.0},
    {"name": "Jasmine Rice 25 KG", "category": "Chinese Grocery", "unit": "BAG", "standard_price": 2200.0, "vendor": "FOOD MONDE", "hsn_code": "10063090", "gst_rate": 5.0},
    {"name": "Jeera Powder 500 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 175.0, "vendor": "LOTS", "hsn_code": "90931", "gst_rate": 5.0},
    {"name": "Jeera Sabut 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 329.0, "vendor": "LOTS", "hsn_code": "90931", "gst_rate": 5.0},
    {"name": "Kaffir Lime Leaves", "category": "Vegetables", "unit": "PKT", "standard_price": 120.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Kala Namak 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 65.0, "vendor": "PRIME FOOD", "hsn_code": "25010010", "gst_rate": 0},
    {"name": "Kashmiri Chilli Whole 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 452.0, "vendor": "HYPERPURE", "hsn_code": "09042110", "gst_rate": 5.0},
    {"name": "Ketchup Heinz 1 KG", "category": "Continental Grocery", "unit": "BTL", "standard_price": 350.0, "vendor": "FOOD MONDE", "hsn_code": "21032000", "gst_rate": 5.0},
    {"name": "Kimchi 1 KG", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 450.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Lamb Leg Boneless", "category": "Non Veg", "unit": "KG", "standard_price": 850.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Lemon Fresh", "category": "Vegetables", "unit": "KG", "standard_price": 80.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Lemongrass", "category": "Vegetables", "unit": "KG", "standard_price": 180.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Lettuce Iceberg", "category": "Vegetables", "unit": "KG", "standard_price": 120.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Light Soya Sauce 1.8 L", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 385.0, "vendor": "FOOD MONDE", "hsn_code": "21031000", "gst_rate": 5.0},
    {"name": "Lotus Root", "category": "Vegetables", "unit": "KG", "standard_price": 350.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Makhani Gravy 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 280.0, "vendor": "PRIME FOOD", "gst_rate": 5.0},
    {"name": "Malai Paneer Fresh", "category": "Dairy Product", "unit": "KG", "standard_price": 340.0, "vendor": "KISHAN BHANDAR", "hsn_code": "406", "gst_rate": 5.0},
    {"name": "Mango Sticky Rice", "category": "Vegetables", "unit": "KG", "standard_price": 250.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Mayonnaise 1 KG", "category": "Continental Grocery", "unit": "JAR", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Methi Fresh", "category": "Vegetables", "unit": "KG", "standard_price": 40.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Milk Full Cream 1 L", "category": "Dairy Product", "unit": "LTR", "standard_price": 68.0, "vendor": "YASH DAIRY", "hsn_code": "401", "gst_rate": 0},
    {"name": "Mint Fresh", "category": "Vegetables", "unit": "KG", "standard_price": 100.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Mirin 1 L", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 420.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Miso Paste White 1 KG", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 650.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "MSG Ajinomoto 1 KG", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "29224990", "gst_rate": 18.0},
    {"name": "Mushroom Button", "category": "Vegetables", "unit": "KG", "standard_price": 220.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Mushroom Oyster", "category": "Vegetables", "unit": "KG", "standard_price": 350.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Mustard Oil 15 L", "category": "Indian Grocery", "unit": "TIN", "standard_price": 2400.0, "vendor": "LOTS", "hsn_code": "15149120", "gst_rate": 5.0},
    {"name": "Mustard Seeds Black", "category": "Indian Grocery", "unit": "PKT", "standard_price": 95.0, "vendor": "PRIME FOOD", "hsn_code": "12074000", "gst_rate": 0},
    {"name": "Naan Bread", "category": "Bakery", "unit": "PCS", "standard_price": 15.0, "vendor": "DREAM OVEN", "hsn_code": "1905", "gst_rate": 0},
    {"name": "Nori Seaweed Sheets", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 450.0, "vendor": "FOOD MONDE", "hsn_code": "12122100", "gst_rate": 5.0},
    {"name": "Olive Black Sliced", "category": "Continental Grocery", "unit": "CAN", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "20057000", "gst_rate": 5.0},
    {"name": "Olive Green Whole", "category": "Continental Grocery", "unit": "JAR", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "20057000", "gst_rate": 5.0},
    {"name": "Onion White", "category": "Vegetables", "unit": "KG", "standard_price": 35.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Oregano Dried", "category": "Continental Grocery", "unit": "PKT", "standard_price": 95.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Oyster Sauce 510 G", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 195.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Pak Choi", "category": "Vegetables", "unit": "KG", "standard_price": 180.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Palm Sugar", "category": "Chinese Grocery", "unit": "KG", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "17011400", "gst_rate": 5.0},
    {"name": "Paneer Fresh", "category": "Dairy Product", "unit": "KG", "standard_price": 320.0, "vendor": "KISHAN BHANDAR", "hsn_code": "406", "gst_rate": 5.0},
    {"name": "Papaya Raw", "category": "Vegetables", "unit": "KG", "standard_price": 40.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Paprika Powder", "category": "Continental Grocery", "unit": "PKT", "standard_price": 180.0, "vendor": "FOOD MONDE", "hsn_code": "9042211", "gst_rate": 5.0},
    {"name": "Parmesan Cheese", "category": "Dairy Product", "unit": "KG", "standard_price": 1800.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Parsley Fresh", "category": "Vegetables", "unit": "KG", "standard_price": 350.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Pasta Penne 500 G", "category": "Continental Grocery", "unit": "PKT", "standard_price": 95.0, "vendor": "FOOD MONDE", "hsn_code": "19021900", "gst_rate": 5.0},
    {"name": "Pasta Spaghetti 500 G", "category": "Continental Grocery", "unit": "PKT", "standard_price": 95.0, "vendor": "FOOD MONDE", "hsn_code": "19021900", "gst_rate": 5.0},
    {"name": "Peanut Butter Creamy", "category": "Indian Grocery", "unit": "JAR", "standard_price": 280.0, "vendor": "LOTS", "hsn_code": "20081110", "gst_rate": 5.0},
    {"name": "Pepper Black Powder", "category": "Indian Grocery", "unit": "PKT", "standard_price": 420.0, "vendor": "LOTS", "hsn_code": "90411", "gst_rate": 5.0},
    {"name": "Pepper Black Whole", "category": "Indian Grocery", "unit": "PKT", "standard_price": 450.0, "vendor": "LOTS", "hsn_code": "90411", "gst_rate": 5.0},
    {"name": "Pepper White Powder", "category": "Indian Grocery", "unit": "PKT", "standard_price": 520.0, "vendor": "LOTS", "hsn_code": "9041200", "gst_rate": 5.0},
    {"name": "Pickle Mixed", "category": "Indian Grocery", "unit": "JAR", "standard_price": 180.0, "vendor": "PRIME FOOD", "hsn_code": "20019000", "gst_rate": 5.0},
    {"name": "Pineapple Fresh", "category": "Vegetables", "unit": "PCS", "standard_price": 80.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Pizza Base 9 Inch", "category": "Bakery", "unit": "PCS", "standard_price": 45.0, "vendor": "DREAM OVEN", "hsn_code": "1905", "gst_rate": 5.0},
    {"name": "Plum Sauce 500 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 220.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Pomegranate", "category": "Fruits & Vegetables", "unit": "KG", "standard_price": 180.0, "vendor": "RAKESH VEGETABLE", "gst_rate": 0},
    {"name": "Potato", "category": "Vegetables", "unit": "KG", "standard_price": 28.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Prawns Medium", "category": "Seafood", "unit": "KG", "standard_price": 650.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Prawns Tiger", "category": "Seafood", "unit": "KG", "standard_price": 1200.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Pumpkin", "category": "Vegetables", "unit": "KG", "standard_price": 35.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Quinoa White 1 KG", "category": "Continental Grocery", "unit": "PKT", "standard_price": 450.0, "vendor": "FOOD MONDE", "hsn_code": "10085090", "gst_rate": 5.0},
    {"name": "Radish White", "category": "Vegetables", "unit": "KG", "standard_price": 25.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Ragi Flour 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 85.0, "vendor": "LOTS", "hsn_code": "11029090", "gst_rate": 0},
    {"name": "Raisin Black 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 280.0, "vendor": "PRIME FOOD", "hsn_code": "08062010", "gst_rate": 0},
    {"name": "Rajma Red 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 145.0, "vendor": "PRIME FOOD", "hsn_code": "7133300", "gst_rate": 0},
    {"name": "Rava Fine 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 55.0, "vendor": "LOTS", "hsn_code": "11031900", "gst_rate": 5.0},
    {"name": "Red Chilli Powder 500 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 165.0, "vendor": "LOTS", "hsn_code": "9042211", "gst_rate": 5.0},
    {"name": "Rice Basmati 25 KG", "category": "Indian Grocery", "unit": "BAG", "standard_price": 2800.0, "vendor": "LOTS", "hsn_code": "10063020", "gst_rate": 5.0},
    {"name": "Rice Paper Round", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 180.0, "vendor": "FOOD MONDE", "hsn_code": "19019090", "gst_rate": 5.0},
    {"name": "Rice Vinegar 500 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 145.0, "vendor": "FOOD MONDE", "hsn_code": "22090090", "gst_rate": 18.0},
    {"name": "Roasted Peanuts 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 180.0, "vendor": "LOTS", "hsn_code": "20081100", "gst_rate": 5.0},
    {"name": "Rosemary Fresh", "category": "Vegetables", "unit": "PKT", "standard_price": 120.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Saffron 1 G", "category": "Indian Grocery", "unit": "PCS", "standard_price": 311.85, "vendor": "PRIME FOOD", "hsn_code": "910", "gst_rate": 5.0},
    {"name": "Salmon Fillet", "category": "Seafood", "unit": "KG", "standard_price": 2200.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Salt Iodized 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 22.0, "vendor": "LOTS", "hsn_code": "25010011", "gst_rate": 0},
    {"name": "Sambal Oelek 500 G", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Schezwan Sauce 1 KG", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Sesame Oil 1 L", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 520.0, "vendor": "FOOD MONDE", "hsn_code": "15155000", "gst_rate": 5.0},
    {"name": "Sesame Seeds Black", "category": "Indian Grocery", "unit": "PKT", "standard_price": 180.0, "vendor": "PRIME FOOD", "hsn_code": "12074000", "gst_rate": 0},
    {"name": "Sesame Seeds White", "category": "Indian Grocery", "unit": "PKT", "standard_price": 165.0, "vendor": "PRIME FOOD", "hsn_code": "12074000", "gst_rate": 0},
    {"name": "Shallots", "category": "Vegetables", "unit": "KG", "standard_price": 120.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Soda Water 750 ML", "category": "Beverage", "unit": "BTL", "standard_price": 25.0, "vendor": "LOTS", "hsn_code": "220110", "gst_rate": 5.0},
    {"name": "Soy Milk 1 L", "category": "Beverage", "unit": "PKT", "standard_price": 95.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Spinach Fresh", "category": "Vegetables", "unit": "KG", "standard_price": 40.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Spring Onion", "category": "Vegetables", "unit": "KG", "standard_price": 80.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Spring Roll Sheet", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 180.0, "vendor": "FOOD MONDE", "hsn_code": "19019090", "gst_rate": 5.0},
    {"name": "Squid Cleaned", "category": "Seafood", "unit": "KG", "standard_price": 450.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Sriracha Sauce 500 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Star Anise 100 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 180.0, "vendor": "PRIME FOOD", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Sugar White 50 KG", "category": "Indian Grocery", "unit": "BAG", "standard_price": 2100.0, "vendor": "LOTS", "hsn_code": "17011990", "gst_rate": 5.0},
    {"name": "Sunflower Oil 15 L", "category": "Indian Grocery", "unit": "TIN", "standard_price": 2200.0, "vendor": "LOTS", "hsn_code": "15121900", "gst_rate": 5.0},
    {"name": "Sweet Chilli Sauce 500 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 185.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Sweet Corn Kernel", "category": "Vegetables", "unit": "KG", "standard_price": 95.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Sweet Potato", "category": "Vegetables", "unit": "KG", "standard_price": 45.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Tamarind Paste 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 145.0, "vendor": "PRIME FOOD", "hsn_code": "20089990", "gst_rate": 5.0},
    {"name": "Tea Leaves 1 KG", "category": "Beverage", "unit": "PKT", "standard_price": 450.0, "vendor": "LOTS", "hsn_code": "9024010", "gst_rate": 5.0},
    {"name": "Thai Basil", "category": "Vegetables", "unit": "KG", "standard_price": 280.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Thai Chilli Paste 2.7 KG", "category": "Chinese Grocery", "unit": "KG", "standard_price": 972.0, "vendor": "FOOD MONDE", "hsn_code": "21032000", "gst_rate": 5.0},
    {"name": "Thyme Dried", "category": "Continental Grocery", "unit": "PKT", "standard_price": 120.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Tissue Roll", "category": "Housekeeping", "unit": "ROLL", "standard_price": 35.0, "vendor": "SHREEJEE", "hsn_code": "48181000", "gst_rate": 18.0},
    {"name": "Tofu Silken", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 85.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Tomato Fresh", "category": "Vegetables", "unit": "KG", "standard_price": 35.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Tomato Ketchup 1 KG", "category": "Indian Grocery", "unit": "BTL", "standard_price": 180.0, "vendor": "LOTS", "hsn_code": "21032000", "gst_rate": 5.0},
    {"name": "Tomato Paste 1 KG", "category": "Continental Grocery", "unit": "CAN", "standard_price": 220.0, "vendor": "FOOD MONDE", "hsn_code": "20029010", "gst_rate": 5.0},
    {"name": "Tonic Water 300 ML", "category": "Beverage", "unit": "BTL", "standard_price": 45.0, "vendor": "LOTS", "hsn_code": "220210", "gst_rate": 40.0},
    {"name": "Turmeric Powder 500 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 95.0, "vendor": "LOTS", "hsn_code": "9103000", "gst_rate": 5.0},
    {"name": "Udon Noodles 1 KG", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "19021900", "gst_rate": 5.0},
    {"name": "Vanilla Extract 100 ML", "category": "Continental Grocery", "unit": "BTL", "standard_price": 450.0, "vendor": "FOOD MONDE", "hsn_code": "13021100", "gst_rate": 5.0},
    {"name": "Vegetable Oil 15 L", "category": "Indian Grocery", "unit": "TIN", "standard_price": 1950.0, "vendor": "LOTS", "hsn_code": "15179090", "gst_rate": 5.0},
    {"name": "Vinegar White 5 L", "category": "Indian Grocery", "unit": "CAN", "standard_price": 180.0, "vendor": "PRIME FOOD", "hsn_code": "22090090", "gst_rate": 18.0},
    {"name": "Walnut 1 KG", "category": "Indian Grocery", "unit": "PKT", "standard_price": 1100.0, "vendor": "PRIME FOOD", "hsn_code": "080231", "gst_rate": 5.0},
    {"name": "Wasabi Paste 43 G", "category": "Chinese Grocery", "unit": "TUBE", "standard_price": 120.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Water Chestnut", "category": "Chinese Grocery", "unit": "CAN", "standard_price": 165.0, "vendor": "FOOD MONDE", "hsn_code": "20059900", "gst_rate": 5.0},
    {"name": "Wheat Flour 10 KG", "category": "Indian Grocery", "unit": "BAG", "standard_price": 420.0, "vendor": "LOTS", "hsn_code": "11010000", "gst_rate": 5.0},
    {"name": "White Pepper Powder", "category": "Indian Grocery", "unit": "PKT", "standard_price": 520.0, "vendor": "LOTS", "hsn_code": "9041200", "gst_rate": 5.0},
    {"name": "Wonton Skin", "category": "Chinese Grocery", "unit": "KG", "standard_price": 180.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Wooden Fork", "category": "Packaging", "unit": "PKT", "standard_price": 35.0, "vendor": "SHREEJEE", "hsn_code": "4421", "gst_rate": 5.0},
    {"name": "Wooden Spoon", "category": "Packaging", "unit": "PKT", "standard_price": 35.0, "vendor": "SHREEJEE", "hsn_code": "4421", "gst_rate": 5.0},
    {"name": "Worcestershire Sauce 150 ML", "category": "Chinese Grocery", "unit": "PCS", "standard_price": 95.0, "vendor": "FOOD MONDE", "hsn_code": "21039020", "gst_rate": 5.0},
    {"name": "Yellow Capsicum", "category": "Vegetables", "unit": "KG", "standard_price": 160.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Yellow Mustard Paste", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 145.0, "vendor": "FOOD MONDE", "hsn_code": "21039040", "gst_rate": 5.0},
    {"name": "Zucchini Green", "category": "Vegetables", "unit": "KG", "standard_price": 120.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Zucchini Yellow", "category": "Vegetables", "unit": "KG", "standard_price": 140.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
]

# Additional items to reach ~683 items (adding more variations)
ADDITIONAL_ITEMS = [
    {"name": "Soy Sauce Dark 500 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 165.0, "vendor": "FOOD MONDE", "hsn_code": "21031000", "gst_rate": 5.0},
    {"name": "Soy Sauce Light 500 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 145.0, "vendor": "FOOD MONDE", "hsn_code": "21031000", "gst_rate": 5.0},
    {"name": "Chilli Oil 250 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 220.0, "vendor": "FOOD MONDE", "hsn_code": "15159090", "gst_rate": 5.0},
    {"name": "Five Spice Powder", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 180.0, "vendor": "FOOD MONDE", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Curry Powder 500 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 195.0, "vendor": "LOTS", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Cinnamon Powder 100 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 125.0, "vendor": "PRIME FOOD", "hsn_code": "9061100", "gst_rate": 5.0},
    {"name": "Cinnamon Stick 100 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 145.0, "vendor": "PRIME FOOD", "hsn_code": "9061100", "gst_rate": 5.0},
    {"name": "Nutmeg Whole", "category": "Indian Grocery", "unit": "PKT", "standard_price": 380.0, "vendor": "PRIME FOOD", "hsn_code": "9081100", "gst_rate": 5.0},
    {"name": "Mace Whole", "category": "Indian Grocery", "unit": "PKT", "standard_price": 950.0, "vendor": "PRIME FOOD", "hsn_code": "9082000", "gst_rate": 5.0},
    {"name": "Ajwain Seeds", "category": "Indian Grocery", "unit": "PKT", "standard_price": 145.0, "vendor": "PRIME FOOD", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Fenugreek Seeds", "category": "Indian Grocery", "unit": "PKT", "standard_price": 85.0, "vendor": "PRIME FOOD", "hsn_code": "12119019", "gst_rate": 0},
    {"name": "Poppy Seeds White", "category": "Indian Grocery", "unit": "PKT", "standard_price": 420.0, "vendor": "PRIME FOOD", "hsn_code": "12079990", "gst_rate": 0},
    {"name": "Asafoetida Powder", "category": "Indian Grocery", "unit": "PKT", "standard_price": 280.0, "vendor": "PRIME FOOD", "hsn_code": "13019099", "gst_rate": 5.0},
    {"name": "Dry Mango Powder", "category": "Indian Grocery", "unit": "PKT", "standard_price": 165.0, "vendor": "LOTS", "hsn_code": "9109929", "gst_rate": 5.0},
    {"name": "Chat Masala 500 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 145.0, "vendor": "LOTS", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Pav Bhaji Masala", "category": "Indian Grocery", "unit": "PKT", "standard_price": 165.0, "vendor": "LOTS", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Biryani Masala", "category": "Indian Grocery", "unit": "PKT", "standard_price": 195.0, "vendor": "LOTS", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Tandoori Masala", "category": "Indian Grocery", "unit": "PKT", "standard_price": 145.0, "vendor": "LOTS", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Chicken Masala", "category": "Indian Grocery", "unit": "PKT", "standard_price": 165.0, "vendor": "LOTS", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Fish Masala", "category": "Indian Grocery", "unit": "PKT", "standard_price": 145.0, "vendor": "LOTS", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Sambar Powder 500 G", "category": "Indian Grocery", "unit": "PKT", "standard_price": 125.0, "vendor": "LOTS", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Rasam Powder", "category": "Indian Grocery", "unit": "PKT", "standard_price": 95.0, "vendor": "LOTS", "hsn_code": "9109990", "gst_rate": 5.0},
    {"name": "Coconut Milk 400 ML", "category": "Chinese Grocery", "unit": "CAN", "standard_price": 145.0, "vendor": "FOOD MONDE", "hsn_code": "20089990", "gst_rate": 5.0},
    {"name": "Coconut Cream 400 ML", "category": "Chinese Grocery", "unit": "CAN", "standard_price": 165.0, "vendor": "FOOD MONDE", "hsn_code": "20089990", "gst_rate": 5.0},
    {"name": "Thai Green Curry Paste", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Thai Red Curry Paste", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Thai Yellow Curry Paste", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Peanut Sauce 500 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 220.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Satay Sauce 500 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 245.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Teriyaki Sauce 500 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 265.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Tonkatsu Sauce 500 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 295.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Ponzu Sauce 355 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Eel Sauce 350 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 380.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Black Bean Sauce 350 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 195.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "XO Sauce 220 G", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 650.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Char Siu Sauce 400 G", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 245.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Lee Kum Kee Oyster Sauce 510 G", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 265.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Shaoxing Wine 750 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 420.0, "vendor": "FOOD MONDE", "hsn_code": "22042100", "gst_rate": 5.0},
    {"name": "Sake Cooking 750 ML", "category": "Chinese Grocery", "unit": "BTL", "standard_price": 480.0, "vendor": "FOOD MONDE", "hsn_code": "22042100", "gst_rate": 5.0},
    {"name": "Dashi Powder 1 KG", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 850.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Bonito Flakes 100 G", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 480.0, "vendor": "FOOD MONDE", "hsn_code": "16042000", "gst_rate": 5.0},
    {"name": "Kombu Kelp 50 G", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "12122100", "gst_rate": 5.0},
    {"name": "Wakame Seaweed 100 G", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "12122100", "gst_rate": 5.0},
    {"name": "Pickled Ginger 1 KG", "category": "Chinese Grocery", "unit": "JAR", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "20019000", "gst_rate": 5.0},
    {"name": "Sushi Rice 5 KG", "category": "Chinese Grocery", "unit": "BAG", "standard_price": 650.0, "vendor": "FOOD MONDE", "hsn_code": "10063090", "gst_rate": 5.0},
    {"name": "Panko Breadcrumb 1 KG", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 245.0, "vendor": "FOOD MONDE", "hsn_code": "19059090", "gst_rate": 5.0},
    {"name": "Tempura Flour 1 KG", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 195.0, "vendor": "FOOD MONDE", "hsn_code": "11010000", "gst_rate": 5.0},
    {"name": "Tonkotsu Ramen Base 1 KG", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 420.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Shoyu Ramen Base 1 KG", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 380.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Miso Ramen Base 1 KG", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 420.0, "vendor": "FOOD MONDE", "hsn_code": "21039090", "gst_rate": 5.0},
    {"name": "Ramen Noodles Fresh 1 KG", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 180.0, "vendor": "FOOD MONDE", "hsn_code": "19021900", "gst_rate": 5.0},
    {"name": "Soba Noodles 500 G", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 220.0, "vendor": "FOOD MONDE", "hsn_code": "19021900", "gst_rate": 5.0},
    {"name": "Shirataki Noodles 200 G", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 145.0, "vendor": "FOOD MONDE", "hsn_code": "19021900", "gst_rate": 5.0},
    {"name": "Enoki Mushroom 200 G", "category": "Vegetables", "unit": "PKT", "standard_price": 180.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "King Oyster Mushroom", "category": "Vegetables", "unit": "KG", "standard_price": 450.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Shimeji Mushroom 150 G", "category": "Vegetables", "unit": "PKT", "standard_price": 220.0, "vendor": "VDEV TRADERS", "gst_rate": 0},
    {"name": "Wood Ear Mushroom Dried", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 320.0, "vendor": "FOOD MONDE", "hsn_code": "20039090", "gst_rate": 5.0},
    {"name": "Bamboo Charcoal Powder", "category": "Chinese Grocery", "unit": "PKT", "standard_price": 450.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Matcha Powder 100 G", "category": "Beverage", "unit": "PKT", "standard_price": 850.0, "vendor": "FOOD MONDE", "hsn_code": "9024010", "gst_rate": 5.0},
    {"name": "Hojicha Powder 100 G", "category": "Beverage", "unit": "PKT", "standard_price": 650.0, "vendor": "FOOD MONDE", "hsn_code": "9024010", "gst_rate": 5.0},
    {"name": "Jasmine Tea 250 G", "category": "Beverage", "unit": "PKT", "standard_price": 380.0, "vendor": "FOOD MONDE", "hsn_code": "9024010", "gst_rate": 5.0},
    {"name": "Oolong Tea 250 G", "category": "Beverage", "unit": "PKT", "standard_price": 420.0, "vendor": "FOOD MONDE", "hsn_code": "9024010", "gst_rate": 5.0},
    {"name": "Green Tea 250 G", "category": "Beverage", "unit": "PKT", "standard_price": 280.0, "vendor": "LOTS", "hsn_code": "9024010", "gst_rate": 5.0},
    {"name": "Black Tea Assam 500 G", "category": "Beverage", "unit": "PKT", "standard_price": 320.0, "vendor": "LOTS", "hsn_code": "9024010", "gst_rate": 5.0},
    {"name": "Darjeeling Tea 250 G", "category": "Beverage", "unit": "PKT", "standard_price": 450.0, "vendor": "LOTS", "hsn_code": "9024010", "gst_rate": 5.0},
    {"name": "Coffee Beans 1 KG", "category": "Beverage", "unit": "PKT", "standard_price": 850.0, "vendor": "LOTS", "hsn_code": "9011100", "gst_rate": 5.0},
    {"name": "Instant Coffee 500 G", "category": "Beverage", "unit": "JAR", "standard_price": 520.0, "vendor": "LOTS", "hsn_code": "21011100", "gst_rate": 5.0},
    {"name": "Cocoa Powder 500 G", "category": "Beverage", "unit": "PKT", "standard_price": 380.0, "vendor": "FOOD MONDE", "hsn_code": "18050000", "gst_rate": 5.0},
    {"name": "Chocolate Chips Dark", "category": "Bakery", "unit": "PKT", "standard_price": 450.0, "vendor": "FOOD MONDE", "hsn_code": "18063200", "gst_rate": 18.0},
    {"name": "Chocolate Chips White", "category": "Bakery", "unit": "PKT", "standard_price": 480.0, "vendor": "FOOD MONDE", "hsn_code": "18063200", "gst_rate": 18.0},
    {"name": "Cooking Chocolate Bar", "category": "Bakery", "unit": "KG", "standard_price": 650.0, "vendor": "FOOD MONDE", "hsn_code": "18063200", "gst_rate": 18.0},
    {"name": "Gelatin Powder 500 G", "category": "Bakery", "unit": "PKT", "standard_price": 850.0, "vendor": "FOOD MONDE", "hsn_code": "35030010", "gst_rate": 18.0},
    {"name": "Agar Agar 100 G", "category": "Bakery", "unit": "PKT", "standard_price": 280.0, "vendor": "FOOD MONDE", "hsn_code": "13023100", "gst_rate": 5.0},
    {"name": "Yeast Active Dry 500 G", "category": "Bakery", "unit": "PKT", "standard_price": 165.0, "vendor": "LOTS", "hsn_code": "21021000", "gst_rate": 5.0},
    {"name": "Baking Soda 1 KG", "category": "Bakery", "unit": "PKT", "standard_price": 85.0, "vendor": "LOTS", "hsn_code": "28363010", "gst_rate": 18.0},
    {"name": "Cream of Tartar 100 G", "category": "Bakery", "unit": "PKT", "standard_price": 145.0, "vendor": "FOOD MONDE", "hsn_code": "29181300", "gst_rate": 18.0},
    {"name": "Food Color Red", "category": "Bakery", "unit": "BTL", "standard_price": 95.0, "vendor": "PRIME FOOD", "hsn_code": "32041200", "gst_rate": 18.0},
    {"name": "Food Color Yellow", "category": "Bakery", "unit": "BTL", "standard_price": 95.0, "vendor": "PRIME FOOD", "hsn_code": "32041200", "gst_rate": 18.0},
    {"name": "Food Color Green", "category": "Bakery", "unit": "BTL", "standard_price": 95.0, "vendor": "PRIME FOOD", "hsn_code": "32041200", "gst_rate": 18.0},
    {"name": "Food Color Blue", "category": "Bakery", "unit": "BTL", "standard_price": 95.0, "vendor": "PRIME FOOD", "hsn_code": "32041200", "gst_rate": 18.0},
    {"name": "Essence Vanilla 100 ML", "category": "Bakery", "unit": "BTL", "standard_price": 85.0, "vendor": "PRIME FOOD", "hsn_code": "33019090", "gst_rate": 18.0},
    {"name": "Essence Strawberry 100 ML", "category": "Bakery", "unit": "BTL", "standard_price": 75.0, "vendor": "PRIME FOOD", "hsn_code": "33019090", "gst_rate": 18.0},
    {"name": "Essence Pineapple 100 ML", "category": "Bakery", "unit": "BTL", "standard_price": 75.0, "vendor": "PRIME FOOD", "hsn_code": "33019090", "gst_rate": 18.0},
    {"name": "Whipping Cream 1 L", "category": "Dairy Product", "unit": "PKT", "standard_price": 380.0, "vendor": "YASH DAIRY", "gst_rate": 5.0},
    {"name": "Mascarpone Cheese 500 G", "category": "Dairy Product", "unit": "TUB", "standard_price": 650.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Ricotta Cheese 450 G", "category": "Dairy Product", "unit": "TUB", "standard_price": 480.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Mozzarella Block 1 KG", "category": "Dairy Product", "unit": "KG", "standard_price": 520.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Mozzarella Shredded 1 KG", "category": "Dairy Product", "unit": "PKT", "standard_price": 550.0, "vendor": "FOOD MONDE", "gst_rate": 5.0},
    {"name": "Processed Cheese Slice", "category": "Dairy Product", "unit": "PKT", "standard_price": 180.0, "vendor": "YASH DAIRY", "gst_rate": 5.0},
    {"name": "Cheese Spread 500 G", "category": "Dairy Product", "unit": "TUB", "standard_price": 245.0, "vendor": "YASH DAIRY", "gst_rate": 5.0},
    {"name": "Cottage Cheese 500 G", "category": "Dairy Product", "unit": "TUB", "standard_price": 280.0, "vendor": "KISHAN BHANDAR", "gst_rate": 5.0},
    {"name": "Hung Curd 1 KG", "category": "Dairy Product", "unit": "KG", "standard_price": 145.0, "vendor": "KISHAN BHANDAR", "gst_rate": 5.0},
    {"name": "Greek Yogurt 500 G", "category": "Dairy Product", "unit": "TUB", "standard_price": 220.0, "vendor": "YASH DAIRY", "gst_rate": 5.0},
    {"name": "Buttermilk 1 L", "category": "Dairy Product", "unit": "BTL", "standard_price": 45.0, "vendor": "YASH DAIRY", "gst_rate": 0},
    {"name": "Condensed Milk 400 G", "category": "Dairy Product", "unit": "CAN", "standard_price": 145.0, "vendor": "LOTS", "hsn_code": "4029120", "gst_rate": 5.0},
    {"name": "Evaporated Milk 400 G", "category": "Dairy Product", "unit": "CAN", "standard_price": 125.0, "vendor": "LOTS", "hsn_code": "4029110", "gst_rate": 5.0},
    {"name": "Skimmed Milk Powder 1 KG", "category": "Dairy Product", "unit": "PKT", "standard_price": 380.0, "vendor": "LOTS", "hsn_code": "4021010", "gst_rate": 5.0},
    {"name": "Khoya Fresh 1 KG", "category": "Dairy Product", "unit": "KG", "standard_price": 420.0, "vendor": "KISHAN BHANDAR", "gst_rate": 5.0},
    {"name": "Mutton Leg Boneless", "category": "Non Veg", "unit": "KG", "standard_price": 780.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Mutton Mince", "category": "Non Veg", "unit": "KG", "standard_price": 650.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Mutton Ribs", "category": "Non Veg", "unit": "KG", "standard_price": 550.0, "vendor": "J P FOOD", "gst_rate": 0},
    {"name": "Chicken Liver", "category": "Non Veg", "unit": "KG", "standard_price": 180.0, "vendor": "VIJAY CHICKEN", "gst_rate": 0},
    {"name": "Chicken Gizzard", "category": "Non Veg", "unit": "KG", "standard_price": 160.0, "vendor": "VIJAY CHICKEN", "gst_rate": 0},
    {"name": "Duck Whole", "category": "Non Veg", "unit": "KG", "standard_price": 520.0, "vendor": "HYPEPURE", "gst_rate": 0},
    {"name": "Duck Breast", "category": "Non Veg", "unit": "KG", "standard_price": 850.0, "vendor": "HYPEPURE", "gst_rate": 0},
    {"name": "Quail Whole", "category": "Non Veg", "unit": "PCS", "standard_price": 180.0, "vendor": "HYPEPURE", "gst_rate": 0},
    {"name": "Turkey Breast", "category": "Non Veg", "unit": "KG", "standard_price": 950.0, "vendor": "HYPEPURE", "gst_rate": 0},
    {"name": "Bacon Strips 200 G", "category": "Non Veg", "unit": "PKT", "standard_price": 380.0, "vendor": "HYPEPURE", "gst_rate": 5.0},
    {"name": "Ham Sliced 200 G", "category": "Non Veg", "unit": "PKT", "standard_price": 320.0, "vendor": "HYPEPURE", "gst_rate": 5.0},
    {"name": "Salami Sliced 200 G", "category": "Non Veg", "unit": "PKT", "standard_price": 420.0, "vendor": "HYPEPURE", "gst_rate": 5.0},
    {"name": "Pepperoni Sliced 200 G", "category": "Non Veg", "unit": "PKT", "standard_price": 450.0, "vendor": "HYPEPURE", "gst_rate": 5.0},
    {"name": "Sausage Chicken 500 G", "category": "Non Veg", "unit": "PKT", "standard_price": 280.0, "vendor": "HYPEPURE", "gst_rate": 5.0},
    {"name": "Sausage Pork 500 G", "category": "Non Veg", "unit": "PKT", "standard_price": 350.0, "vendor": "HYPEPURE", "gst_rate": 5.0},
    {"name": "Fish Basa Fillet", "category": "Seafood", "unit": "KG", "standard_price": 380.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Fish Rawas", "category": "Seafood", "unit": "KG", "standard_price": 650.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Fish Pomfret", "category": "Seafood", "unit": "KG", "standard_price": 850.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Fish Surmai", "category": "Seafood", "unit": "KG", "standard_price": 720.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Fish Rohu", "category": "Seafood", "unit": "KG", "standard_price": 280.0, "vendor": "JP FOOD", "gst_rate": 0},
    {"name": "Fish Catla", "category": "Seafood", "unit": "KG", "standard_price": 250.0, "vendor": "JP FOOD", "gst_rate": 0},
    {"name": "Crab Live", "category": "Seafood", "unit": "KG", "standard_price": 1200.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Lobster Whole", "category": "Seafood", "unit": "KG", "standard_price": 2800.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Oyster Fresh", "category": "Seafood", "unit": "DZN", "standard_price": 650.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Scallop", "category": "Seafood", "unit": "KG", "standard_price": 1800.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Clam", "category": "Seafood", "unit": "KG", "standard_price": 480.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Mussel", "category": "Seafood", "unit": "KG", "standard_price": 380.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Octopus Cleaned", "category": "Seafood", "unit": "KG", "standard_price": 950.0, "vendor": "MK HOSPITALITY", "gst_rate": 5.0},
    {"name": "Paper Cup 250 ML", "category": "Packaging", "unit": "PKT", "standard_price": 180.0, "vendor": "ECOTEGRITY", "hsn_code": "48193000", "gst_rate": 18.0},
    {"name": "Paper Cup 350 ML", "category": "Packaging", "unit": "PKT", "standard_price": 220.0, "vendor": "ECOTEGRITY", "hsn_code": "48193000", "gst_rate": 18.0},
    {"name": "Paper Bag Brown", "category": "Packaging", "unit": "PKT", "standard_price": 145.0, "vendor": "ECOTEGRITY", "hsn_code": "48191000", "gst_rate": 18.0},
    {"name": "Paper Straw", "category": "Packaging", "unit": "PKT", "standard_price": 120.0, "vendor": "ECOTEGRITY", "hsn_code": "48239090", "gst_rate": 18.0},
    {"name": "Plastic Straw", "category": "Packaging", "unit": "PKT", "standard_price": 45.0, "vendor": "SHREEJEE", "hsn_code": "39241000", "gst_rate": 18.0},
    {"name": "Plastic Spoon", "category": "Packaging", "unit": "PKT", "standard_price": 55.0, "vendor": "SHREEJEE", "hsn_code": "39241000", "gst_rate": 18.0},
    {"name": "Plastic Fork", "category": "Packaging", "unit": "PKT", "standard_price": 55.0, "vendor": "SHREEJEE", "hsn_code": "39241000", "gst_rate": 18.0},
    {"name": "Aluminium Foil 72 M", "category": "Packaging", "unit": "ROLL", "standard_price": 480.0, "vendor": "SHREEJEE", "hsn_code": "76071900", "gst_rate": 18.0},
    {"name": "Aluminium Container 250 ML", "category": "Packaging", "unit": "PKT", "standard_price": 280.0, "vendor": "SHREEJEE", "hsn_code": "76129010", "gst_rate": 18.0},
    {"name": "Aluminium Container 450 ML", "category": "Packaging", "unit": "PKT", "standard_price": 350.0, "vendor": "SHREEJEE", "hsn_code": "76129010", "gst_rate": 18.0},
    {"name": "Aluminium Container 660 ML", "category": "Packaging", "unit": "PKT", "standard_price": 420.0, "vendor": "SHREEJEE", "hsn_code": "76129010", "gst_rate": 18.0},
    {"name": "Ziplock Bag Small", "category": "Packaging", "unit": "PKT", "standard_price": 85.0, "vendor": "SHREEJEE", "hsn_code": "39232990", "gst_rate": 18.0},
    {"name": "Ziplock Bag Medium", "category": "Packaging", "unit": "PKT", "standard_price": 125.0, "vendor": "SHREEJEE", "hsn_code": "39232990", "gst_rate": 18.0},
    {"name": "Ziplock Bag Large", "category": "Packaging", "unit": "PKT", "standard_price": 165.0, "vendor": "SHREEJEE", "hsn_code": "39232990", "gst_rate": 18.0},
    {"name": "Garbage Bag Black", "category": "Housekeeping", "unit": "PKT", "standard_price": 145.0, "vendor": "SHREEJEE", "hsn_code": "39232990", "gst_rate": 18.0},
    {"name": "Hand Gloves Disposable", "category": "Housekeeping", "unit": "BOX", "standard_price": 320.0, "vendor": "SHREEJEE", "hsn_code": "40151200", "gst_rate": 18.0},
    {"name": "Apron Disposable", "category": "Housekeeping", "unit": "PKT", "standard_price": 180.0, "vendor": "SHREEJEE", "hsn_code": "39262090", "gst_rate": 18.0},
    {"name": "Dish Wash Liquid 5 L", "category": "Housekeeping", "unit": "CAN", "standard_price": 380.0, "vendor": "LOTS", "hsn_code": "34022090", "gst_rate": 18.0},
    {"name": "Floor Cleaner 5 L", "category": "Housekeeping", "unit": "CAN", "standard_price": 280.0, "vendor": "LOTS", "hsn_code": "34022090", "gst_rate": 18.0},
    {"name": "Glass Cleaner 5 L", "category": "Housekeeping", "unit": "CAN", "standard_price": 320.0, "vendor": "LOTS", "hsn_code": "34022090", "gst_rate": 18.0},
    {"name": "Hand Wash Liquid 5 L", "category": "Housekeeping", "unit": "CAN", "standard_price": 450.0, "vendor": "LOTS", "hsn_code": "34011100", "gst_rate": 18.0},
    {"name": "Sanitizer 500 ML", "category": "Housekeeping", "unit": "BTL", "standard_price": 180.0, "vendor": "LOTS", "hsn_code": "38089410", "gst_rate": 18.0},
    {"name": "Toilet Cleaner 1 L", "category": "Housekeeping", "unit": "BTL", "standard_price": 145.0, "vendor": "LOTS", "hsn_code": "34022090", "gst_rate": 18.0},
    {"name": "Scrub Pad Green", "category": "Housekeeping", "unit": "PCS", "standard_price": 25.0, "vendor": "SHREEJEE", "hsn_code": "68052000", "gst_rate": 18.0},
    {"name": "Steel Scrubber", "category": "Housekeeping", "unit": "PCS", "standard_price": 35.0, "vendor": "SHREEJEE", "hsn_code": "73231000", "gst_rate": 18.0},
    {"name": "Mop Refill", "category": "Housekeeping", "unit": "PCS", "standard_price": 145.0, "vendor": "SHREEJEE", "hsn_code": "96039000", "gst_rate": 18.0},
    {"name": "Broom Soft", "category": "Housekeeping", "unit": "PCS", "standard_price": 120.0, "vendor": "SHREEJEE", "hsn_code": "96039000", "gst_rate": 18.0},
    {"name": "Dustpan Set", "category": "Housekeeping", "unit": "SET", "standard_price": 180.0, "vendor": "SHREEJEE", "hsn_code": "96039000", "gst_rate": 18.0},
]

# Combine all items
ALL_ITEMS = ITEMS + ADDITIONAL_ITEMS

def hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()

async def seed_database():
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    print("Starting DREAMOVEN database seeding...")
    
    # Clear existing data
    print("Clearing existing data...")
    await db.users.delete_many({})
    await db.kitchens.delete_many({})
    await db.categories.delete_many({})
    await db.vendors.delete_many({})
    await db.items.delete_many({})
    await db.stock.delete_many({})
    await db.purchase_orders.delete_many({})
    
    # Seed Admin User
    print("Creating admin user...")
    admin_user = {
        "id": str(uuid.uuid4()),
        "email": "parveenkatyal2312@gmail.com",
        "password": hash_password("admin@123"),
        "name": "Admin",
        "role": "admin",
        "created_at": datetime.now(timezone.utc).isoformat()
    }
    await db.users.insert_one(admin_user)
    print(f"  Admin user created: {admin_user['email']}")
    
    # Seed Kitchens
    print(f"Creating {len(KITCHENS)} kitchens...")
    for kitchen in KITCHENS:
        kitchen_doc = {
            "id": str(uuid.uuid4()),
            "name": kitchen["name"],
            "code": kitchen["code"],
            "address": "",
            "is_main_store": kitchen["is_main_store"],
            "created_at": datetime.now(timezone.utc).isoformat()
        }
        await db.kitchens.insert_one(kitchen_doc)
    print(f"  {len(KITCHENS)} kitchens created")
    
    # Seed Categories
    print(f"Creating {len(CATEGORIES)} categories...")
    for cat_name in CATEGORIES:
        category_doc = {
            "id": str(uuid.uuid4()),
            "name": cat_name,
            "created_at": datetime.now(timezone.utc).isoformat()
        }
        await db.categories.insert_one(category_doc)
    print(f"  {len(CATEGORIES)} categories created")
    
    # Seed Vendors
    print(f"Creating {len(VENDORS)} vendors...")
    for vendor in VENDORS:
        vendor_doc = {
            "id": str(uuid.uuid4()),
            "name": vendor["name"],
            "contact": "",
            "email": "",
            "phone": "",
            "address": "",
            "gst_number": "",
            "payment_terms": "Net 30",
            "supply_categories": vendor["supply_categories"],
            "created_at": datetime.now(timezone.utc).isoformat()
        }
        await db.vendors.insert_one(vendor_doc)
    print(f"  {len(VENDORS)} vendors created")
    
    # Seed Items
    print(f"Creating {len(ALL_ITEMS)} items...")
    for item in ALL_ITEMS:
        item_doc = {
            "id": str(uuid.uuid4()),
            "name": item["name"],
            "category": item["category"],
            "unit": item["unit"],
            "hsn_code": item.get("hsn_code", ""),
            "gst_rate": item.get("gst_rate", 0),
            "vendor": item.get("vendor", ""),
            "standard_price": item.get("standard_price"),
            "par_stock": None,
            "created_at": datetime.now(timezone.utc).isoformat()
        }
        await db.items.insert_one(item_doc)
    print(f"  {len(ALL_ITEMS)} items created")
    
    # Summary
    print("\n" + "="*50)
    print("DREAMOVEN Database Seeding Complete!")
    print("="*50)
    print(f"  Admin User: parveenkatyal2312@gmail.com")
    print(f"  Password: admin@123")
    print(f"  Kitchens: {len(KITCHENS)} (including Main Store)")
    print(f"  Categories: {len(CATEGORIES)}")
    print(f"  Vendors: {len(VENDORS)}")
    print(f"  Items: {len(ALL_ITEMS)}")
    print("="*50)
    
    client.close()

if __name__ == "__main__":
    asyncio.run(seed_database())
